// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tutor.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTutor = `-- name: CreateTutor :exec
INSERT INTO tutor (course_phase_id, id, first_name, last_name, email, matriculation_number, university_login)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateTutorParams struct {
	CoursePhaseID       uuid.UUID `json:"course_phase_id"`
	ID                  uuid.UUID `json:"id"`
	FirstName           string    `json:"first_name"`
	LastName            string    `json:"last_name"`
	Email               string    `json:"email"`
	MatriculationNumber string    `json:"matriculation_number"`
	UniversityLogin     string    `json:"university_login"`
}

func (q *Queries) CreateTutor(ctx context.Context, arg CreateTutorParams) error {
	_, err := q.db.Exec(ctx, createTutor,
		arg.CoursePhaseID,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.MatriculationNumber,
		arg.UniversityLogin,
	)
	return err
}
