// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assessment_schema.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAssessmentSchema = `-- name: CreateAssessmentSchema :exec
INSERT INTO assessment_schema (id, name, description, created_at, updated_at)
VALUES ($1, $2, $3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`

type CreateAssessmentSchemaParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateAssessmentSchema(ctx context.Context, arg CreateAssessmentSchemaParams) error {
	_, err := q.db.Exec(ctx, createAssessmentSchema, arg.ID, arg.Name, arg.Description)
	return err
}

const deleteAssessmentSchema = `-- name: DeleteAssessmentSchema :exec
DELETE
FROM assessment_schema
WHERE id = $1
`

func (q *Queries) DeleteAssessmentSchema(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssessmentSchema, id)
	return err
}

const getAssessmentSchema = `-- name: GetAssessmentSchema :one
SELECT id, name, description, created_at, updated_at
FROM assessment_schema
WHERE id = $1
`

func (q *Queries) GetAssessmentSchema(ctx context.Context, id uuid.UUID) (AssessmentSchema, error) {
	row := q.db.QueryRow(ctx, getAssessmentSchema, id)
	var i AssessmentSchema
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssessmentSchemaByName = `-- name: GetAssessmentSchemaByName :one
SELECT id, name, description, created_at, updated_at
FROM assessment_schema
WHERE name = $1
`

func (q *Queries) GetAssessmentSchemaByName(ctx context.Context, name string) (AssessmentSchema, error) {
	row := q.db.QueryRow(ctx, getAssessmentSchemaByName, name)
	var i AssessmentSchema
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssessmentSchemas = `-- name: ListAssessmentSchemas :many
SELECT id, name, description, created_at, updated_at
FROM assessment_schema
ORDER BY name ASC
`

func (q *Queries) ListAssessmentSchemas(ctx context.Context) ([]AssessmentSchema, error) {
	rows, err := q.db.Query(ctx, listAssessmentSchemas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssessmentSchema
	for rows.Next() {
		var i AssessmentSchema
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssessmentSchema = `-- name: UpdateAssessmentSchema :exec
UPDATE assessment_schema
SET name        = $2,
    description = $3,
    updated_at  = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateAssessmentSchemaParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateAssessmentSchema(ctx context.Context, arg UpdateAssessmentSchemaParams) error {
	_, err := q.db.Exec(ctx, updateAssessmentSchema, arg.ID, arg.Name, arg.Description)
	return err
}
