// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: assessment.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAssessment = `-- name: DeleteAssessment :exec
DELETE FROM assessment
WHERE id = $1
  AND course_participation_id = $2
  AND course_phase_id = $3
`

type DeleteAssessmentParams struct {
	ID                    uuid.UUID `json:"id"`
	CourseParticipationID uuid.UUID `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID `json:"course_phase_id"`
}

func (q *Queries) DeleteAssessment(ctx context.Context, arg DeleteAssessmentParams) error {
	_, err := q.db.Exec(ctx, deleteAssessment, arg.ID, arg.CourseParticipationID, arg.CoursePhaseID)
	return err
}

const getAssessmentByCompetency = `-- name: GetAssessmentByCompetency :one
SELECT id, course_participation_id, course_phase_id, competency_id, score, comment, assessed_at
FROM assessment
WHERE course_participation_id = $1
  AND course_phase_id = $2
  AND competency_id = $3
`

type GetAssessmentByCompetencyParams struct {
	CourseParticipationID uuid.UUID `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID `json:"course_phase_id"`
	CompetencyID          uuid.UUID `json:"competency_id"`
}

func (q *Queries) GetAssessmentByCompetency(ctx context.Context, arg GetAssessmentByCompetencyParams) (Assessment, error) {
	row := q.db.QueryRow(ctx, getAssessmentByCompetency, arg.CourseParticipationID, arg.CoursePhaseID, arg.CompetencyID)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.CourseParticipationID,
		&i.CoursePhaseID,
		&i.CompetencyID,
		&i.Score,
		&i.Comment,
		&i.AssessedAt,
	)
	return i, err
}

const getAssessmentsForStudentInPhase = `-- name: GetAssessmentsForStudentInPhase :many
SELECT id, course_participation_id, course_phase_id, competency_id, score, comment, assessed_at
FROM assessment
WHERE course_participation_id = $1
  AND course_phase_id = $2
ORDER BY assessed_at DESC
`

type GetAssessmentsForStudentInPhaseParams struct {
	CourseParticipationID uuid.UUID `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID `json:"course_phase_id"`
}

func (q *Queries) GetAssessmentsForStudentInPhase(ctx context.Context, arg GetAssessmentsForStudentInPhaseParams) ([]Assessment, error) {
	rows, err := q.db.Query(ctx, getAssessmentsForStudentInPhase, arg.CourseParticipationID, arg.CoursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assessment
	for rows.Next() {
		var i Assessment
		if err := rows.Scan(
			&i.ID,
			&i.CourseParticipationID,
			&i.CoursePhaseID,
			&i.CompetencyID,
			&i.Score,
			&i.Comment,
			&i.AssessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAssessment = `-- name: InsertAssessment :exec
INSERT INTO assessment (id, course_participation_id, course_phase_id, competency_id, score, comment, assessed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAssessmentParams struct {
	ID                    uuid.UUID        `json:"id"`
	CourseParticipationID uuid.UUID        `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID        `json:"course_phase_id"`
	CompetencyID          uuid.UUID        `json:"competency_id"`
	Score                 int16            `json:"score"`
	Comment               pgtype.Text      `json:"comment"`
	AssessedAt            pgtype.Timestamp `json:"assessed_at"`
}

func (q *Queries) InsertAssessment(ctx context.Context, arg InsertAssessmentParams) error {
	_, err := q.db.Exec(ctx, insertAssessment,
		arg.ID,
		arg.CourseParticipationID,
		arg.CoursePhaseID,
		arg.CompetencyID,
		arg.Score,
		arg.Comment,
		arg.AssessedAt,
	)
	return err
}

const updateAssessment = `-- name: UpdateAssessment :exec
UPDATE assessment
SET score = $4,
    comment = $5,
    assessed_at = $6
WHERE id = $1
  AND course_participation_id = $2
  AND course_phase_id = $3
`

type UpdateAssessmentParams struct {
	ID                    uuid.UUID        `json:"id"`
	CourseParticipationID uuid.UUID        `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID        `json:"course_phase_id"`
	Score                 int16            `json:"score"`
	Comment               pgtype.Text      `json:"comment"`
	AssessedAt            pgtype.Timestamp `json:"assessed_at"`
}

func (q *Queries) UpdateAssessment(ctx context.Context, arg UpdateAssessmentParams) error {
	_, err := q.db.Exec(ctx, updateAssessment,
		arg.ID,
		arg.CourseParticipationID,
		arg.CoursePhaseID,
		arg.Score,
		arg.Comment,
		arg.AssessedAt,
	)
	return err
}
