// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: competency.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCompetency = `-- name: CreateCompetency :one
INSERT INTO competency (
    id, category_id, name, description, novice,
    intermediate, advanced, expert, weight
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, category_id, name, description, novice, intermediate, advanced, expert, weight
`

type CreateCompetencyParams struct {
	ID           uuid.UUID   `json:"id"`
	CategoryID   uuid.UUID   `json:"category_id"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	Novice       string      `json:"novice"`
	Intermediate string      `json:"intermediate"`
	Advanced     string      `json:"advanced"`
	Expert       string      `json:"expert"`
	Weight       int32       `json:"weight"`
}

func (q *Queries) CreateCompetency(ctx context.Context, arg CreateCompetencyParams) (Competency, error) {
	row := q.db.QueryRow(ctx, createCompetency,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Novice,
		arg.Intermediate,
		arg.Advanced,
		arg.Expert,
		arg.Weight,
	)
	var i Competency
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Novice,
		&i.Intermediate,
		&i.Advanced,
		&i.Expert,
		&i.Weight,
	)
	return i, err
}

const deleteCompetency = `-- name: DeleteCompetency :exec
DELETE FROM competency WHERE id = $1
`

func (q *Queries) DeleteCompetency(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompetency, id)
	return err
}

const getCompetency = `-- name: GetCompetency :one
SELECT id, category_id, name, description, novice, intermediate, advanced, expert, weight FROM competency WHERE id = $1
`

func (q *Queries) GetCompetency(ctx context.Context, id uuid.UUID) (Competency, error) {
	row := q.db.QueryRow(ctx, getCompetency, id)
	var i Competency
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Novice,
		&i.Intermediate,
		&i.Advanced,
		&i.Expert,
		&i.Weight,
	)
	return i, err
}

const listCompetencies = `-- name: ListCompetencies :many
SELECT id, category_id, name, description, novice, intermediate, advanced, expert, weight FROM competency
`

func (q *Queries) ListCompetencies(ctx context.Context) ([]Competency, error) {
	rows, err := q.db.Query(ctx, listCompetencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Competency
	for rows.Next() {
		var i Competency
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Novice,
			&i.Intermediate,
			&i.Advanced,
			&i.Expert,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompetenciesByCategory = `-- name: ListCompetenciesByCategory :many
SELECT id, category_id, name, description, novice, intermediate, advanced, expert, weight FROM competency WHERE category_id = $1
`

func (q *Queries) ListCompetenciesByCategory(ctx context.Context, categoryID uuid.UUID) ([]Competency, error) {
	rows, err := q.db.Query(ctx, listCompetenciesByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Competency
	for rows.Next() {
		var i Competency
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Novice,
			&i.Intermediate,
			&i.Advanced,
			&i.Expert,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompetency = `-- name: UpdateCompetency :one
UPDATE competency
SET category_id = $2,
    name = $3,
    description = $4,
    novice = $5,
    intermediate = $6,
    advanced = $7,
    expert = $8,
    weight = $9
WHERE id = $1
RETURNING id, category_id, name, description, novice, intermediate, advanced, expert, weight
`

type UpdateCompetencyParams struct {
	ID           uuid.UUID   `json:"id"`
	CategoryID   uuid.UUID   `json:"category_id"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	Novice       string      `json:"novice"`
	Intermediate string      `json:"intermediate"`
	Advanced     string      `json:"advanced"`
	Expert       string      `json:"expert"`
	Weight       int32       `json:"weight"`
}

func (q *Queries) UpdateCompetency(ctx context.Context, arg UpdateCompetencyParams) (Competency, error) {
	row := q.db.QueryRow(ctx, updateCompetency,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Novice,
		arg.Intermediate,
		arg.Advanced,
		arg.Expert,
		arg.Weight,
	)
	var i Competency
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Novice,
		&i.Intermediate,
		&i.Advanced,
		&i.Expert,
		&i.Weight,
	)
	return i, err
}
