// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Assessment struct {
	ID                    uuid.UUID        `json:"id"`
	CourseParticipationID uuid.UUID        `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID        `json:"course_phase_id"`
	CompetencyID          uuid.UUID        `json:"competency_id"`
	Score                 int16            `json:"score"`
	Comment               pgtype.Text      `json:"comment"`
	AssessedAt            pgtype.Timestamp `json:"assessed_at"`
}

type Category struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type Competency struct {
	ID           uuid.UUID   `json:"id"`
	CategoryID   uuid.UUID   `json:"category_id"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	Novice       string      `json:"novice"`
	Intermediate string      `json:"intermediate"`
	Advanced     string      `json:"advanced"`
	Expert       string      `json:"expert"`
}
