openapi: 3.1.0
info:
  title: Challenge API
  description: API for managing GitHub challenge submissions and testing student containers.
  version: 1.0.0
paths:
  /{coursePhaseID}/demo-student:
    get:
      summary: Demo endpoint for students
      description: A protected demo endpoint accessible only to students.
      parameters:
        - name: coursePhaseID
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Hello, student'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /{coursePhaseID}/demo-lecturer:
    get:
      summary: Demo endpoint for lecturers
      description: A protected demo endpoint accessible to lecturers and admins.
      parameters:
        - name: coursePhaseID
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Hello, student'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /{coursePhaseID}/info:
    get:
      summary: Get student info
      description: Returns repository and challenge status for the authenticated student.
      parameters:
        - name: coursePhaseID
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Student info retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  repositoryUrl:
                    type: string
                  attempts:
                    type: integer
                  maxAttempts:
                    type: integer
                  hasPassed:
                    type: boolean
        '400':
          description: Invalid coursePhaseID or missing authentication context
        '404':
          description: Student not found

  /{coursePhaseID}/students:
    get:
      summary: Get all students
      description: Returns all students registered for the course phase. Requires lecturer or admin role.
      parameters:
        - name: coursePhaseID
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of students
          content:
            application/json:
              schema:
                type: object
                properties:
                  students:
                    type: array
                    items:
                      type: object
                      properties:
                        ID:
                          type: integer
                        CourseParticipationId:
                          type: string
                        StudentId:
                          type: string
                        GithubUsername:
                          type: string
                        Repository:
                          type: string
                        Passed:
                          type: boolean
                        Attempts:
                          type: integer
                        VariantBaseImage:
                          type: string
                        VariantJavaVersion:
                          type: integer
                        VariantPort:
                          type: integer
                        VariantRestCallPath:
                          type: string
        '400':
          description: Invalid coursePhaseID

  /{coursePhaseID}/repository:
    post:
      summary: Create student repository
      description: Creates a GitHub repository and registers the student in the database.
      parameters:
        - name: coursePhaseID
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - githubUsername
              properties:
                githubUsername:
                  type: string
      responses:
        '200':
          description: Repository created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  repositoryUrl:
                    type: string
        '400':
          description: Invalid input or GitHub username
        '409':
          description: Student already exists

  /{coursePhaseID}/studentTest:
    post:
      summary: Test student challenge
      description: Pulls the student’s container, runs it, and checks correctness.
      parameters:
        - name: coursePhaseID
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Student passed challenge
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Student passed challenge'
        '400':
          description: Student has no repository or container
        '500':
          description: Error during testing
