// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: name.sql

package db

import (
	"context"
)

const getName = `-- name: GetName :many
SELECT name
FROM template_table
`

func (q *Queries) GetName(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
