// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: application.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const batchUpdateAdditionalScores = `-- name: BatchUpdateAdditionalScores :exec
WITH updates AS (
  SELECT 
    UNNEST($1::uuid[]) AS id,
    UNNEST($2::numeric[]) AS score,
    $3::text[] AS path -- Use $3 as a JSON path array
)
UPDATE course_phase_participation
SET    
    restricted_data = jsonb_set(
        COALESCE(restricted_data, '{}'),
        updates.path, -- Use dynamic path
        to_jsonb(ROUND(updates.score, 2)) -- Convert the float score to JSONB
    )
FROM updates
WHERE 
    course_phase_participation.id = updates.id
    AND course_phase_participation.course_phase_id = $4
`

type BatchUpdateAdditionalScoresParams struct {
	Column1       []uuid.UUID      `json:"column_1"`
	Column2       []pgtype.Numeric `json:"column_2"`
	Column3       []string         `json:"column_3"`
	CoursePhaseID uuid.UUID        `json:"course_phase_id"`
}

func (q *Queries) BatchUpdateAdditionalScores(ctx context.Context, arg BatchUpdateAdditionalScoresParams) error {
	_, err := q.db.Exec(ctx, batchUpdateAdditionalScores,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.CoursePhaseID,
	)
	return err
}

const checkCoursePhaseParticipationPair = `-- name: CheckCoursePhaseParticipationPair :one
SELECT EXISTS (
    SELECT 1
    FROM course_phase_participation cpp
    WHERE cpp.id = $1
      AND cpp.course_phase_id = $2
)
`

type CheckCoursePhaseParticipationPairParams struct {
	ID            uuid.UUID `json:"id"`
	CoursePhaseID uuid.UUID `json:"course_phase_id"`
}

func (q *Queries) CheckCoursePhaseParticipationPair(ctx context.Context, arg CheckCoursePhaseParticipationPairParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkCoursePhaseParticipationPair, arg.ID, arg.CoursePhaseID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkIfCoursePhaseIsApplicationPhase = `-- name: CheckIfCoursePhaseIsApplicationPhase :one
SELECT 
    cpt.name = 'Application' AS is_application
FROM 
    course_phase cp
JOIN 
    course_phase_type cpt
ON 
    cp.course_phase_type_id = cpt.id
WHERE 
    cp.id = $1
`

func (q *Queries) CheckIfCoursePhaseIsApplicationPhase(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkIfCoursePhaseIsApplicationPhase, id)
	var is_application bool
	err := row.Scan(&is_application)
	return is_application, err
}

const checkIfCoursePhaseIsOpenApplicationPhase = `-- name: CheckIfCoursePhaseIsOpenApplicationPhase :one
SELECT 
    cpt.name = 'Application' AS is_application,
    (cp.restricted_data->>'universityLoginAvailable')::boolean AS university_login_available 
FROM 
    course_phase cp
JOIN 
    course_phase_type cpt
ON 
    cp.course_phase_type_id = cpt.id
WHERE 
    cp.id = $1
    AND (cp.restricted_data->>'applicationEndDate')::timestamp > NOW()
`

type CheckIfCoursePhaseIsOpenApplicationPhaseRow struct {
	IsApplication            bool `json:"is_application"`
	UniversityLoginAvailable bool `json:"university_login_available"`
}

func (q *Queries) CheckIfCoursePhaseIsOpenApplicationPhase(ctx context.Context, id uuid.UUID) (CheckIfCoursePhaseIsOpenApplicationPhaseRow, error) {
	row := q.db.QueryRow(ctx, checkIfCoursePhaseIsOpenApplicationPhase, id)
	var i CheckIfCoursePhaseIsOpenApplicationPhaseRow
	err := row.Scan(&i.IsApplication, &i.UniversityLoginAvailable)
	return i, err
}

const createApplicationAnswerMultiSelect = `-- name: CreateApplicationAnswerMultiSelect :exec
INSERT INTO application_answer_multi_select (id, application_question_id, course_phase_participation_id, answer)
VALUES ($1, $2, $3, $4)
`

type CreateApplicationAnswerMultiSelectParams struct {
	ID                         uuid.UUID `json:"id"`
	ApplicationQuestionID      uuid.UUID `json:"application_question_id"`
	CoursePhaseParticipationID uuid.UUID `json:"course_phase_participation_id"`
	Answer                     []string  `json:"answer"`
}

func (q *Queries) CreateApplicationAnswerMultiSelect(ctx context.Context, arg CreateApplicationAnswerMultiSelectParams) error {
	_, err := q.db.Exec(ctx, createApplicationAnswerMultiSelect,
		arg.ID,
		arg.ApplicationQuestionID,
		arg.CoursePhaseParticipationID,
		arg.Answer,
	)
	return err
}

const createApplicationAnswerText = `-- name: CreateApplicationAnswerText :exec
INSERT INTO application_answer_text (id, application_question_id, course_phase_participation_id, answer)
VALUES ($1, $2, $3, $4)
`

type CreateApplicationAnswerTextParams struct {
	ID                         uuid.UUID   `json:"id"`
	ApplicationQuestionID      uuid.UUID   `json:"application_question_id"`
	CoursePhaseParticipationID uuid.UUID   `json:"course_phase_participation_id"`
	Answer                     pgtype.Text `json:"answer"`
}

func (q *Queries) CreateApplicationAnswerText(ctx context.Context, arg CreateApplicationAnswerTextParams) error {
	_, err := q.db.Exec(ctx, createApplicationAnswerText,
		arg.ID,
		arg.ApplicationQuestionID,
		arg.CoursePhaseParticipationID,
		arg.Answer,
	)
	return err
}

const createApplicationQuestionMultiSelect = `-- name: CreateApplicationQuestionMultiSelect :exec
INSERT INTO application_question_multi_select (id, course_phase_id, title, description, placeholder, error_message, is_required, min_select, max_select, options, order_num, accessible_for_other_phases, access_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateApplicationQuestionMultiSelectParams struct {
	ID                       uuid.UUID   `json:"id"`
	CoursePhaseID            uuid.UUID   `json:"course_phase_id"`
	Title                    pgtype.Text `json:"title"`
	Description              pgtype.Text `json:"description"`
	Placeholder              pgtype.Text `json:"placeholder"`
	ErrorMessage             pgtype.Text `json:"error_message"`
	IsRequired               pgtype.Bool `json:"is_required"`
	MinSelect                pgtype.Int4 `json:"min_select"`
	MaxSelect                pgtype.Int4 `json:"max_select"`
	Options                  []string    `json:"options"`
	OrderNum                 pgtype.Int4 `json:"order_num"`
	AccessibleForOtherPhases pgtype.Bool `json:"accessible_for_other_phases"`
	AccessKey                pgtype.Text `json:"access_key"`
}

func (q *Queries) CreateApplicationQuestionMultiSelect(ctx context.Context, arg CreateApplicationQuestionMultiSelectParams) error {
	_, err := q.db.Exec(ctx, createApplicationQuestionMultiSelect,
		arg.ID,
		arg.CoursePhaseID,
		arg.Title,
		arg.Description,
		arg.Placeholder,
		arg.ErrorMessage,
		arg.IsRequired,
		arg.MinSelect,
		arg.MaxSelect,
		arg.Options,
		arg.OrderNum,
		arg.AccessibleForOtherPhases,
		arg.AccessKey,
	)
	return err
}

const createApplicationQuestionText = `-- name: CreateApplicationQuestionText :exec
INSERT INTO application_question_text (id, course_phase_id, title, description, placeholder, validation_regex, error_message, is_required, allowed_length, order_num, accessible_for_other_phases, access_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateApplicationQuestionTextParams struct {
	ID                       uuid.UUID   `json:"id"`
	CoursePhaseID            uuid.UUID   `json:"course_phase_id"`
	Title                    pgtype.Text `json:"title"`
	Description              pgtype.Text `json:"description"`
	Placeholder              pgtype.Text `json:"placeholder"`
	ValidationRegex          pgtype.Text `json:"validation_regex"`
	ErrorMessage             pgtype.Text `json:"error_message"`
	IsRequired               pgtype.Bool `json:"is_required"`
	AllowedLength            pgtype.Int4 `json:"allowed_length"`
	OrderNum                 pgtype.Int4 `json:"order_num"`
	AccessibleForOtherPhases pgtype.Bool `json:"accessible_for_other_phases"`
	AccessKey                pgtype.Text `json:"access_key"`
}

func (q *Queries) CreateApplicationQuestionText(ctx context.Context, arg CreateApplicationQuestionTextParams) error {
	_, err := q.db.Exec(ctx, createApplicationQuestionText,
		arg.ID,
		arg.CoursePhaseID,
		arg.Title,
		arg.Description,
		arg.Placeholder,
		arg.ValidationRegex,
		arg.ErrorMessage,
		arg.IsRequired,
		arg.AllowedLength,
		arg.OrderNum,
		arg.AccessibleForOtherPhases,
		arg.AccessKey,
	)
	return err
}

const createOrOverwriteApplicationAnswerMultiSelect = `-- name: CreateOrOverwriteApplicationAnswerMultiSelect :exec
INSERT INTO application_answer_multi_select (id, application_question_id, course_phase_participation_id, answer)
VALUES ($1, $2, $3, $4)
ON CONFLICT (course_phase_participation_id, application_question_id)
DO UPDATE
SET answer = EXCLUDED.answer
`

type CreateOrOverwriteApplicationAnswerMultiSelectParams struct {
	ID                         uuid.UUID `json:"id"`
	ApplicationQuestionID      uuid.UUID `json:"application_question_id"`
	CoursePhaseParticipationID uuid.UUID `json:"course_phase_participation_id"`
	Answer                     []string  `json:"answer"`
}

func (q *Queries) CreateOrOverwriteApplicationAnswerMultiSelect(ctx context.Context, arg CreateOrOverwriteApplicationAnswerMultiSelectParams) error {
	_, err := q.db.Exec(ctx, createOrOverwriteApplicationAnswerMultiSelect,
		arg.ID,
		arg.ApplicationQuestionID,
		arg.CoursePhaseParticipationID,
		arg.Answer,
	)
	return err
}

const createOrOverwriteApplicationAnswerText = `-- name: CreateOrOverwriteApplicationAnswerText :exec
INSERT INTO application_answer_text (id, application_question_id, course_phase_participation_id, answer)
VALUES ($1, $2, $3, $4)
ON CONFLICT (course_phase_participation_id, application_question_id)
DO UPDATE
SET answer = EXCLUDED.answer
`

type CreateOrOverwriteApplicationAnswerTextParams struct {
	ID                         uuid.UUID   `json:"id"`
	ApplicationQuestionID      uuid.UUID   `json:"application_question_id"`
	CoursePhaseParticipationID uuid.UUID   `json:"course_phase_participation_id"`
	Answer                     pgtype.Text `json:"answer"`
}

func (q *Queries) CreateOrOverwriteApplicationAnswerText(ctx context.Context, arg CreateOrOverwriteApplicationAnswerTextParams) error {
	_, err := q.db.Exec(ctx, createOrOverwriteApplicationAnswerText,
		arg.ID,
		arg.ApplicationQuestionID,
		arg.CoursePhaseParticipationID,
		arg.Answer,
	)
	return err
}

const deleteApplicationQuestionMultiSelect = `-- name: DeleteApplicationQuestionMultiSelect :exec
DELETE FROM application_question_multi_select
WHERE id = $1
`

func (q *Queries) DeleteApplicationQuestionMultiSelect(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplicationQuestionMultiSelect, id)
	return err
}

const deleteApplicationQuestionText = `-- name: DeleteApplicationQuestionText :exec
DELETE FROM application_question_text
WHERE id = $1
`

func (q *Queries) DeleteApplicationQuestionText(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplicationQuestionText, id)
	return err
}

const deleteApplications = `-- name: DeleteApplications :exec
DELETE FROM course_participation
WHERE id IN (
      SELECT cpp.course_participation_id
      FROM course_phase_participation cpp
      WHERE cpp.id = ANY($2::uuid[])
        AND cpp.course_phase_id = $1 -- ensures that only applications for the given course phase are deleted
  )
`

type DeleteApplicationsParams struct {
	CoursePhaseID uuid.UUID   `json:"course_phase_id"`
	Column2       []uuid.UUID `json:"column_2"`
}

func (q *Queries) DeleteApplications(ctx context.Context, arg DeleteApplicationsParams) error {
	_, err := q.db.Exec(ctx, deleteApplications, arg.CoursePhaseID, arg.Column2)
	return err
}

const getAllApplicationParticipations = `-- name: GetAllApplicationParticipations :many
SELECT
    cpp.id AS course_phase_participation_id,
    cpp.pass_status,
    cpp.restricted_data,
    s.id AS student_id,
    s.first_name,
    s.last_name,
    s.email,
    s.matriculation_number,
    s.university_login,
    s.has_university_account,
    s.gender, 
    s.nationality,
    s.study_degree,
    s.study_program,
    s.current_semester,
    a.score
FROM
    course_phase_participation cpp
JOIN
    course_participation cp ON cpp.course_participation_id = cp.id
JOIN
    student s ON cp.student_id = s.id
LEFT JOIN
    application_assessment a on cpp.id = a.course_phase_participation_id
WHERE
    cpp.course_phase_id = $1
`

type GetAllApplicationParticipationsRow struct {
	CoursePhaseParticipationID uuid.UUID      `json:"course_phase_participation_id"`
	PassStatus                 NullPassStatus `json:"pass_status"`
	RestrictedData             []byte         `json:"restricted_data"`
	StudentID                  uuid.UUID      `json:"student_id"`
	FirstName                  pgtype.Text    `json:"first_name"`
	LastName                   pgtype.Text    `json:"last_name"`
	Email                      pgtype.Text    `json:"email"`
	MatriculationNumber        pgtype.Text    `json:"matriculation_number"`
	UniversityLogin            pgtype.Text    `json:"university_login"`
	HasUniversityAccount       pgtype.Bool    `json:"has_university_account"`
	Gender                     Gender         `json:"gender"`
	Nationality                pgtype.Text    `json:"nationality"`
	StudyDegree                StudyDegree    `json:"study_degree"`
	StudyProgram               pgtype.Text    `json:"study_program"`
	CurrentSemester            pgtype.Int4    `json:"current_semester"`
	Score                      pgtype.Int4    `json:"score"`
}

func (q *Queries) GetAllApplicationParticipations(ctx context.Context, coursePhaseID uuid.UUID) ([]GetAllApplicationParticipationsRow, error) {
	rows, err := q.db.Query(ctx, getAllApplicationParticipations, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllApplicationParticipationsRow
	for rows.Next() {
		var i GetAllApplicationParticipationsRow
		if err := rows.Scan(
			&i.CoursePhaseParticipationID,
			&i.PassStatus,
			&i.RestrictedData,
			&i.StudentID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.MatriculationNumber,
			&i.UniversityLogin,
			&i.HasUniversityAccount,
			&i.Gender,
			&i.Nationality,
			&i.StudyDegree,
			&i.StudyProgram,
			&i.CurrentSemester,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllOpenApplicationPhases = `-- name: GetAllOpenApplicationPhases :many
SELECT 
    cp.id AS course_phase_id,
    c.name AS course_name,
    c.start_date, 
    c.end_date,
    c.course_type, 
    c.ects,
    (cp.restricted_data->>'applicationEndDate')::text AS application_end_date,
    (cp.restricted_data->>'externalStudentsAllowed')::boolean AS external_students_allowed,
    (cp.restricted_data->>'universityLoginAvailable')::boolean AS university_login_available
FROM 
    course_phase cp
JOIN 
    course_phase_type cpt
    ON cp.course_phase_type_id = cpt.id
JOIN 
    course c
    ON cp.course_id = c.id
WHERE 
    cp.is_initial_phase = true
    AND cpt.name = 'Application'
    AND (cp.restricted_data->>'applicationEndDate')::timestamp > NOW()
    AND (cp.restricted_data->>'applicationStartDate')::timestamp < NOW()
`

type GetAllOpenApplicationPhasesRow struct {
	CoursePhaseID            uuid.UUID   `json:"course_phase_id"`
	CourseName               string      `json:"course_name"`
	StartDate                pgtype.Date `json:"start_date"`
	EndDate                  pgtype.Date `json:"end_date"`
	CourseType               CourseType  `json:"course_type"`
	Ects                     pgtype.Int4 `json:"ects"`
	ApplicationEndDate       string      `json:"application_end_date"`
	ExternalStudentsAllowed  bool        `json:"external_students_allowed"`
	UniversityLoginAvailable bool        `json:"university_login_available"`
}

func (q *Queries) GetAllOpenApplicationPhases(ctx context.Context) ([]GetAllOpenApplicationPhasesRow, error) {
	rows, err := q.db.Query(ctx, getAllOpenApplicationPhases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllOpenApplicationPhasesRow
	for rows.Next() {
		var i GetAllOpenApplicationPhasesRow
		if err := rows.Scan(
			&i.CoursePhaseID,
			&i.CourseName,
			&i.StartDate,
			&i.EndDate,
			&i.CourseType,
			&i.Ects,
			&i.ApplicationEndDate,
			&i.ExternalStudentsAllowed,
			&i.UniversityLoginAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationAnswersMultiSelectForStudent = `-- name: GetApplicationAnswersMultiSelectForStudent :many
SELECT aams.id, aams.application_question_id, aams.course_phase_participation_id, aams.answer
FROM application_answer_multi_select aams
INNER JOIN course_phase_participation cpp ON aams.course_phase_participation_id = cpp.id
INNER JOIN course_participation cp ON cpp.course_participation_id = cp.id
WHERE cp.student_id = $1 AND cpp.course_phase_id = $2
`

type GetApplicationAnswersMultiSelectForStudentParams struct {
	StudentID     uuid.UUID `json:"student_id"`
	CoursePhaseID uuid.UUID `json:"course_phase_id"`
}

func (q *Queries) GetApplicationAnswersMultiSelectForStudent(ctx context.Context, arg GetApplicationAnswersMultiSelectForStudentParams) ([]ApplicationAnswerMultiSelect, error) {
	rows, err := q.db.Query(ctx, getApplicationAnswersMultiSelectForStudent, arg.StudentID, arg.CoursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationAnswerMultiSelect
	for rows.Next() {
		var i ApplicationAnswerMultiSelect
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationQuestionID,
			&i.CoursePhaseParticipationID,
			&i.Answer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationAnswersTextForStudent = `-- name: GetApplicationAnswersTextForStudent :many
SELECT aat.id, aat.application_question_id, aat.course_phase_participation_id, aat.answer
FROM application_answer_text aat
INNER JOIN course_phase_participation cpp ON aat.course_phase_participation_id = cpp.id
INNER JOIN course_participation cp ON cpp.course_participation_id = cp.id
WHERE cp.student_id = $1 AND cpp.course_phase_id = $2
`

type GetApplicationAnswersTextForStudentParams struct {
	StudentID     uuid.UUID `json:"student_id"`
	CoursePhaseID uuid.UUID `json:"course_phase_id"`
}

func (q *Queries) GetApplicationAnswersTextForStudent(ctx context.Context, arg GetApplicationAnswersTextForStudentParams) ([]ApplicationAnswerText, error) {
	rows, err := q.db.Query(ctx, getApplicationAnswersTextForStudent, arg.StudentID, arg.CoursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationAnswerText
	for rows.Next() {
		var i ApplicationAnswerText
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationQuestionID,
			&i.CoursePhaseParticipationID,
			&i.Answer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationExists = `-- name: GetApplicationExists :one
SELECT EXISTS (
    SELECT 1
    FROM course_phase_participation cpp
    WHERE cpp.course_phase_id = $1
    AND cpp.id = $2
)
`

type GetApplicationExistsParams struct {
	CoursePhaseID uuid.UUID `json:"course_phase_id"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) GetApplicationExists(ctx context.Context, arg GetApplicationExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, getApplicationExists, arg.CoursePhaseID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getApplicationExistsForStudent = `-- name: GetApplicationExistsForStudent :one
SELECT EXISTS (
    SELECT 1
    FROM course_participation cp
    INNER JOIN course_phase ph ON cp.course_id = ph.course_id
    WHERE cp.student_id = $1 AND ph.id = $2
)
`

type GetApplicationExistsForStudentParams struct {
	StudentID uuid.UUID `json:"student_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetApplicationExistsForStudent(ctx context.Context, arg GetApplicationExistsForStudentParams) (bool, error) {
	row := q.db.QueryRow(ctx, getApplicationExistsForStudent, arg.StudentID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getApplicationQuestionsMultiSelectForCoursePhase = `-- name: GetApplicationQuestionsMultiSelectForCoursePhase :many
SELECT id, course_phase_id, title, description, placeholder, error_message, is_required, min_select, max_select, options, order_num, accessible_for_other_phases, access_key FROM application_question_multi_select
WHERE course_phase_id = $1
`

func (q *Queries) GetApplicationQuestionsMultiSelectForCoursePhase(ctx context.Context, coursePhaseID uuid.UUID) ([]ApplicationQuestionMultiSelect, error) {
	rows, err := q.db.Query(ctx, getApplicationQuestionsMultiSelectForCoursePhase, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationQuestionMultiSelect
	for rows.Next() {
		var i ApplicationQuestionMultiSelect
		if err := rows.Scan(
			&i.ID,
			&i.CoursePhaseID,
			&i.Title,
			&i.Description,
			&i.Placeholder,
			&i.ErrorMessage,
			&i.IsRequired,
			&i.MinSelect,
			&i.MaxSelect,
			&i.Options,
			&i.OrderNum,
			&i.AccessibleForOtherPhases,
			&i.AccessKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationQuestionsTextForCoursePhase = `-- name: GetApplicationQuestionsTextForCoursePhase :many
SELECT id, course_phase_id, title, description, placeholder, validation_regex, error_message, is_required, allowed_length, order_num, accessible_for_other_phases, access_key FROM application_question_text
WHERE course_phase_id = $1
`

func (q *Queries) GetApplicationQuestionsTextForCoursePhase(ctx context.Context, coursePhaseID uuid.UUID) ([]ApplicationQuestionText, error) {
	rows, err := q.db.Query(ctx, getApplicationQuestionsTextForCoursePhase, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationQuestionText
	for rows.Next() {
		var i ApplicationQuestionText
		if err := rows.Scan(
			&i.ID,
			&i.CoursePhaseID,
			&i.Title,
			&i.Description,
			&i.Placeholder,
			&i.ValidationRegex,
			&i.ErrorMessage,
			&i.IsRequired,
			&i.AllowedLength,
			&i.OrderNum,
			&i.AccessibleForOtherPhases,
			&i.AccessKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExistingAdditionalScores = `-- name: GetExistingAdditionalScores :one
SELECT 
    restricted_data->>'additional_scores' AS additional_scores
FROM
    course_phase
WHERE
    id = $1
`

func (q *Queries) GetExistingAdditionalScores(ctx context.Context, id uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getExistingAdditionalScores, id)
	var additional_scores interface{}
	err := row.Scan(&additional_scores)
	return additional_scores, err
}

const getOpenApplicationPhase = `-- name: GetOpenApplicationPhase :one
SELECT 
    cp.id AS course_phase_id,
    c.name AS course_name,
    c.start_date, 
    c.end_date,
    c.course_type, 
    c.ects,
    (cp.restricted_data->>'applicationEndDate')::text AS application_end_date,
    (cp.restricted_data->>'externalStudentsAllowed')::boolean AS external_students_allowed,
    (cp.restricted_data->>'universityLoginAvailable')::boolean AS university_login_available
FROM 
    course_phase cp
JOIN 
    course_phase_type cpt
    ON cp.course_phase_type_id = cpt.id
JOIN 
    course c
    ON cp.course_id = c.id
WHERE 
    cp.id = $1
    AND cp.is_initial_phase = true
    AND cpt.name = 'Application'
    AND (cp.restricted_data->>'applicationEndDate')::timestamp > NOW()
    AND (cp.restricted_data->>'applicationStartDate')::timestamp < NOW()
`

type GetOpenApplicationPhaseRow struct {
	CoursePhaseID            uuid.UUID   `json:"course_phase_id"`
	CourseName               string      `json:"course_name"`
	StartDate                pgtype.Date `json:"start_date"`
	EndDate                  pgtype.Date `json:"end_date"`
	CourseType               CourseType  `json:"course_type"`
	Ects                     pgtype.Int4 `json:"ects"`
	ApplicationEndDate       string      `json:"application_end_date"`
	ExternalStudentsAllowed  bool        `json:"external_students_allowed"`
	UniversityLoginAvailable bool        `json:"university_login_available"`
}

func (q *Queries) GetOpenApplicationPhase(ctx context.Context, id uuid.UUID) (GetOpenApplicationPhaseRow, error) {
	row := q.db.QueryRow(ctx, getOpenApplicationPhase, id)
	var i GetOpenApplicationPhaseRow
	err := row.Scan(
		&i.CoursePhaseID,
		&i.CourseName,
		&i.StartDate,
		&i.EndDate,
		&i.CourseType,
		&i.Ects,
		&i.ApplicationEndDate,
		&i.ExternalStudentsAllowed,
		&i.UniversityLoginAvailable,
	)
	return i, err
}

const storeApplicationAnswerUpdateTimestamp = `-- name: StoreApplicationAnswerUpdateTimestamp :exec
UPDATE course_phase_participation
SET restricted_data = jsonb_set(
    COALESCE(restricted_data, '{}'), -- Ensure meta_data is not NULL
    '{student_last_modified}', -- Path to the key
    to_jsonb(NOW())::jsonb     -- Value to set
)
WHERE id = $1
`

func (q *Queries) StoreApplicationAnswerUpdateTimestamp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, storeApplicationAnswerUpdateTimestamp, id)
	return err
}

const storeApplicationAssessmentUpdateTimestamp = `-- name: StoreApplicationAssessmentUpdateTimestamp :exec
UPDATE course_phase_participation
SET restricted_data = jsonb_set(
    COALESCE(restricted_data, '{}'), -- Ensure meta_data is not NULL
    '{assessment_last_modified}', -- Path to the key
    to_jsonb(NOW())::jsonb     -- Value to set
)
WHERE id = $1
`

func (q *Queries) StoreApplicationAssessmentUpdateTimestamp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, storeApplicationAssessmentUpdateTimestamp, id)
	return err
}

const updateApplicationAssessment = `-- name: UpdateApplicationAssessment :exec
INSERT INTO application_assessment (id, course_phase_participation_id, score)
VALUES (
    gen_random_uuid(),    
    $1,                   
    $2             
)
ON CONFLICT (course_phase_participation_id) 
DO UPDATE 
SET score = EXCLUDED.score
`

type UpdateApplicationAssessmentParams struct {
	CoursePhaseParticipationID uuid.UUID   `json:"course_phase_participation_id"`
	Score                      pgtype.Int4 `json:"score"`
}

func (q *Queries) UpdateApplicationAssessment(ctx context.Context, arg UpdateApplicationAssessmentParams) error {
	_, err := q.db.Exec(ctx, updateApplicationAssessment, arg.CoursePhaseParticipationID, arg.Score)
	return err
}

const updateApplicationQuestionMultiSelect = `-- name: UpdateApplicationQuestionMultiSelect :exec
UPDATE application_question_multi_select
SET
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    placeholder = COALESCE($4, placeholder),
    error_message = COALESCE($5, error_message),
    is_required = COALESCE($6, is_required),
    min_select = COALESCE($7, min_select),
    max_select = COALESCE($8, max_select),
    options = COALESCE($9, options),
    order_num = COALESCE($10, order_num), 
    accessible_for_other_phases = COALESCE($11, accessible_for_other_phases),
    access_key = COALESCE($12, access_key)
WHERE id = $1
`

type UpdateApplicationQuestionMultiSelectParams struct {
	ID                       uuid.UUID   `json:"id"`
	Title                    pgtype.Text `json:"title"`
	Description              pgtype.Text `json:"description"`
	Placeholder              pgtype.Text `json:"placeholder"`
	ErrorMessage             pgtype.Text `json:"error_message"`
	IsRequired               pgtype.Bool `json:"is_required"`
	MinSelect                pgtype.Int4 `json:"min_select"`
	MaxSelect                pgtype.Int4 `json:"max_select"`
	Options                  []string    `json:"options"`
	OrderNum                 pgtype.Int4 `json:"order_num"`
	AccessibleForOtherPhases pgtype.Bool `json:"accessible_for_other_phases"`
	AccessKey                pgtype.Text `json:"access_key"`
}

func (q *Queries) UpdateApplicationQuestionMultiSelect(ctx context.Context, arg UpdateApplicationQuestionMultiSelectParams) error {
	_, err := q.db.Exec(ctx, updateApplicationQuestionMultiSelect,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Placeholder,
		arg.ErrorMessage,
		arg.IsRequired,
		arg.MinSelect,
		arg.MaxSelect,
		arg.Options,
		arg.OrderNum,
		arg.AccessibleForOtherPhases,
		arg.AccessKey,
	)
	return err
}

const updateApplicationQuestionText = `-- name: UpdateApplicationQuestionText :exec
UPDATE application_question_text
SET
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    placeholder = COALESCE($4, placeholder),
    validation_regex = COALESCE($5, validation_regex),
    error_message = COALESCE($6, error_message),
    is_required = COALESCE($7, is_required),
    allowed_length = COALESCE($8, allowed_length),
    order_num = COALESCE($9, order_num),
    accessible_for_other_phases = COALESCE($10, accessible_for_other_phases),
    access_key = COALESCE($11, access_key)
WHERE id = $1
`

type UpdateApplicationQuestionTextParams struct {
	ID                       uuid.UUID   `json:"id"`
	Title                    pgtype.Text `json:"title"`
	Description              pgtype.Text `json:"description"`
	Placeholder              pgtype.Text `json:"placeholder"`
	ValidationRegex          pgtype.Text `json:"validation_regex"`
	ErrorMessage             pgtype.Text `json:"error_message"`
	IsRequired               pgtype.Bool `json:"is_required"`
	AllowedLength            pgtype.Int4 `json:"allowed_length"`
	OrderNum                 pgtype.Int4 `json:"order_num"`
	AccessibleForOtherPhases pgtype.Bool `json:"accessible_for_other_phases"`
	AccessKey                pgtype.Text `json:"access_key"`
}

func (q *Queries) UpdateApplicationQuestionText(ctx context.Context, arg UpdateApplicationQuestionTextParams) error {
	_, err := q.db.Exec(ctx, updateApplicationQuestionText,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Placeholder,
		arg.ValidationRegex,
		arg.ErrorMessage,
		arg.IsRequired,
		arg.AllowedLength,
		arg.OrderNum,
		arg.AccessibleForOtherPhases,
		arg.AccessKey,
	)
	return err
}

const updateExistingAdditionalScores = `-- name: UpdateExistingAdditionalScores :exec
UPDATE course_phase
SET restricted_data = restricted_data || $2
WHERE id = $1
`

type UpdateExistingAdditionalScoresParams struct {
	ID             uuid.UUID `json:"id"`
	RestrictedData []byte    `json:"restricted_data"`
}

func (q *Queries) UpdateExistingAdditionalScores(ctx context.Context, arg UpdateExistingAdditionalScoresParams) error {
	_, err := q.db.Exec(ctx, updateExistingAdditionalScores, arg.ID, arg.RestrictedData)
	return err
}
