// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: course_phase_type.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCoursePhaseType = `-- name: CreateCoursePhaseType :exec
INSERT INTO course_phase_type (id, name, initial_phase, base_url)
VALUES ($1, $2, $3, $4)
`

type CreateCoursePhaseTypeParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	InitialPhase bool      `json:"initial_phase"`
	BaseUrl      string    `json:"base_url"`
}

func (q *Queries) CreateCoursePhaseType(ctx context.Context, arg CreateCoursePhaseTypeParams) error {
	_, err := q.db.Exec(ctx, createCoursePhaseType,
		arg.ID,
		arg.Name,
		arg.InitialPhase,
		arg.BaseUrl,
	)
	return err
}

const createCoursePhaseTypeProvidedOutput = `-- name: CreateCoursePhaseTypeProvidedOutput :exec
INSERT INTO course_phase_type_participation_provided_output_dto (id, course_phase_type_id, dto_name, version_number, endpoint_path, specification)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateCoursePhaseTypeProvidedOutputParams struct {
	ID                uuid.UUID `json:"id"`
	CoursePhaseTypeID uuid.UUID `json:"course_phase_type_id"`
	DtoName           string    `json:"dto_name"`
	VersionNumber     int32     `json:"version_number"`
	EndpointPath      string    `json:"endpoint_path"`
	Specification     []byte    `json:"specification"`
}

func (q *Queries) CreateCoursePhaseTypeProvidedOutput(ctx context.Context, arg CreateCoursePhaseTypeProvidedOutputParams) error {
	_, err := q.db.Exec(ctx, createCoursePhaseTypeProvidedOutput,
		arg.ID,
		arg.CoursePhaseTypeID,
		arg.DtoName,
		arg.VersionNumber,
		arg.EndpointPath,
		arg.Specification,
	)
	return err
}

const createCoursePhaseTypeRequiredInput = `-- name: CreateCoursePhaseTypeRequiredInput :exec
INSERT INTO course_phase_type_participation_required_input_dto (id, course_phase_type_id, dto_name, specification)
VALUES ($1, $2, $3, $4)
`

type CreateCoursePhaseTypeRequiredInputParams struct {
	ID                uuid.UUID `json:"id"`
	CoursePhaseTypeID uuid.UUID `json:"course_phase_type_id"`
	DtoName           string    `json:"dto_name"`
	Specification     []byte    `json:"specification"`
}

func (q *Queries) CreateCoursePhaseTypeRequiredInput(ctx context.Context, arg CreateCoursePhaseTypeRequiredInputParams) error {
	_, err := q.db.Exec(ctx, createCoursePhaseTypeRequiredInput,
		arg.ID,
		arg.CoursePhaseTypeID,
		arg.DtoName,
		arg.Specification,
	)
	return err
}

const createInterviewRequiredApplicationAnswers = `-- name: CreateInterviewRequiredApplicationAnswers :exec
INSERT INTO course_phase_type_participation_required_input_dto (id, course_phase_type_id, dto_name, specification)
VALUES (
       gen_random_uuid(),
       $1,
       'applicationAnswers',    
       '{
            "type": "array",
            "items": {
                "oneOf": [
                {
                    "type": "object",
                    "properties": {
                    "answer"   : { "type": "string"                    },
                    "key"      : { "type": "string"                    },
                    "order_num": { "type": "integer"                   },
                    "type"     : { "type": "string" , "enum": ["text"] }
                    },
                    "required": ["answer", "key", "order_num", "type"]
                },
                {
                    "type": "object",
                    "properties": {
                    "answer"   : { "type": "array", "items": {"type": "string"} },
                    "key"      : {"type": "string"}                              ,
                    "order_num": {"type": "integer"}                             ,
                    "type"     : { "type": "string", "enum": ["multiselect"] }
                    },
                    "required": ["answer", "key", "order_num", "type"]
                }
                ]
            }
       }'::jsonb
)
`

func (q *Queries) CreateInterviewRequiredApplicationAnswers(ctx context.Context, coursePhaseTypeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createInterviewRequiredApplicationAnswers, coursePhaseTypeID)
	return err
}

const getAllCoursePhaseTypes = `-- name: GetAllCoursePhaseTypes :many
SELECT id, name, initial_phase, base_url FROM course_phase_type
`

func (q *Queries) GetAllCoursePhaseTypes(ctx context.Context) ([]CoursePhaseType, error) {
	rows, err := q.db.Query(ctx, getAllCoursePhaseTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursePhaseType
	for rows.Next() {
		var i CoursePhaseType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InitialPhase,
			&i.BaseUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursePhaseProvidedParticipationOutputs = `-- name: GetCoursePhaseProvidedParticipationOutputs :many
SELECT id, course_phase_type_id, dto_name, version_number, endpoint_path, specification
FROM course_phase_type_participation_provided_output_dto
WHERE course_phase_type_id = $1
`

func (q *Queries) GetCoursePhaseProvidedParticipationOutputs(ctx context.Context, coursePhaseTypeID uuid.UUID) ([]CoursePhaseTypeParticipationProvidedOutputDto, error) {
	rows, err := q.db.Query(ctx, getCoursePhaseProvidedParticipationOutputs, coursePhaseTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursePhaseTypeParticipationProvidedOutputDto
	for rows.Next() {
		var i CoursePhaseTypeParticipationProvidedOutputDto
		if err := rows.Scan(
			&i.ID,
			&i.CoursePhaseTypeID,
			&i.DtoName,
			&i.VersionNumber,
			&i.EndpointPath,
			&i.Specification,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursePhaseProvidedPhaseOutputs = `-- name: GetCoursePhaseProvidedPhaseOutputs :many
SELECT id, course_phase_type_id, dto_name, version_number, endpoint_path, specification
FROM course_phase_type_phase_provided_output_dto
WHERE course_phase_type_id = $1
`

func (q *Queries) GetCoursePhaseProvidedPhaseOutputs(ctx context.Context, coursePhaseTypeID uuid.UUID) ([]CoursePhaseTypePhaseProvidedOutputDto, error) {
	rows, err := q.db.Query(ctx, getCoursePhaseProvidedPhaseOutputs, coursePhaseTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursePhaseTypePhaseProvidedOutputDto
	for rows.Next() {
		var i CoursePhaseTypePhaseProvidedOutputDto
		if err := rows.Scan(
			&i.ID,
			&i.CoursePhaseTypeID,
			&i.DtoName,
			&i.VersionNumber,
			&i.EndpointPath,
			&i.Specification,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursePhaseRequiredParticipationInputs = `-- name: GetCoursePhaseRequiredParticipationInputs :many
SELECT id, course_phase_type_id, dto_name, specification
FROM course_phase_type_participation_required_input_dto
WHERE course_phase_type_id = $1
`

func (q *Queries) GetCoursePhaseRequiredParticipationInputs(ctx context.Context, coursePhaseTypeID uuid.UUID) ([]CoursePhaseTypeParticipationRequiredInputDto, error) {
	rows, err := q.db.Query(ctx, getCoursePhaseRequiredParticipationInputs, coursePhaseTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursePhaseTypeParticipationRequiredInputDto
	for rows.Next() {
		var i CoursePhaseTypeParticipationRequiredInputDto
		if err := rows.Scan(
			&i.ID,
			&i.CoursePhaseTypeID,
			&i.DtoName,
			&i.Specification,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursePhaseRequiredPhaseInputs = `-- name: GetCoursePhaseRequiredPhaseInputs :many
SELECT id, course_phase_type_id, dto_name, specification
FROM course_phase_type_phase_required_input_dto
WHERE course_phase_type_id = $1
`

func (q *Queries) GetCoursePhaseRequiredPhaseInputs(ctx context.Context, coursePhaseTypeID uuid.UUID) ([]CoursePhaseTypePhaseRequiredInputDto, error) {
	rows, err := q.db.Query(ctx, getCoursePhaseRequiredPhaseInputs, coursePhaseTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursePhaseTypePhaseRequiredInputDto
	for rows.Next() {
		var i CoursePhaseTypePhaseRequiredInputDto
		if err := rows.Scan(
			&i.ID,
			&i.CoursePhaseTypeID,
			&i.DtoName,
			&i.Specification,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCourseProvidedAdditionalScores = `-- name: InsertCourseProvidedAdditionalScores :exec
INSERT INTO course_phase_type_participation_provided_output_dto (id, course_phase_type_id, dto_name, version_number, endpoint_path, specification)
VALUES (
      gen_random_uuid(),
      $1,
      'additionalScores',
      1,
      'core',
      '{
            "type": "array",
            "items": {
                "type": "object",
                "properties": { "score": {"type": "number"}, "key": {"type": "string"} },
                "required": ["score", "key"]
            }
        }'::jsonb
)
`

func (q *Queries) InsertCourseProvidedAdditionalScores(ctx context.Context, coursePhaseTypeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertCourseProvidedAdditionalScores, coursePhaseTypeID)
	return err
}

const insertCourseProvidedApplicationAnswers = `-- name: InsertCourseProvidedApplicationAnswers :exec
INSERT INTO course_phase_type_participation_provided_output_dto (id, course_phase_type_id, dto_name, version_number, endpoint_path, specification)
VALUES (
      gen_random_uuid(),
      $1,
      'applicationAnswers',
      1,
      'core',
      '{
            "type": "array",
            "items": {
                "oneOf": [
                {
                    "type": "object",
                    "properties": {
                    "answer"   : { "type": "string"                    },
                    "key"      : { "type": "string"                    },
                    "order_num": { "type": "integer"                   },
                    "type"     : { "type": "string" , "enum": ["text"] }
                    },
                    "required": ["answer", "key", "order_num", "type"]
                },
                {
                    "type": "object",
                    "properties": {
                    "answer"   : { "type": "array", "items": {"type": "string"} },
                    "key"      : {"type": "string"}                              ,
                    "order_num": {"type": "integer"}                             ,
                    "type"     : { "type": "string", "enum": ["multiselect"] }
                    },
                    "required": ["answer", "key", "order_num", "type"]
                }
                ]
            }
       }'::jsonb
)
`

func (q *Queries) InsertCourseProvidedApplicationAnswers(ctx context.Context, coursePhaseTypeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertCourseProvidedApplicationAnswers, coursePhaseTypeID)
	return err
}

const insertDeveloperProfileOutput = `-- name: InsertDeveloperProfileOutput :exec
INSERT INTO course_phase_type_participation_provided_output_dto (id, course_phase_type_id, dto_name, version_number, endpoint_path, specification)
VALUES (
      gen_random_uuid(),
      $1,
      'developerProfile',
      1,
      '/developer-profile',
      '{
            "type": "object",
            "properties": {
                "appleID"           : {"type": "string"},
                "gitLabID"          : {"type": "string"},
                "macBookUUID"       : {"type": "string"},
                "iphoneUUID"        : {"type": "string"},
                "ipadUUID"          : {"type": "string"},
                "appleWatchUUID"    : {"type": "string"}
            },
            "required": ["appleID", "gitLabID"]
        }'::jsonb
)
`

func (q *Queries) InsertDeveloperProfileOutput(ctx context.Context, coursePhaseTypeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertDeveloperProfileOutput, coursePhaseTypeID)
	return err
}

const insertProficiencyLevelOutput = `-- name: InsertProficiencyLevelOutput :exec
INSERT INTO course_phase_type_participation_provided_output_dto (id, course_phase_type_id, dto_name, version_number, endpoint_path, specification)
VALUES (
      gen_random_uuid(),
      $1,
      'proficiency',
      1,
      '/proficiency',
      '{
            "type": "string",
            "enum": ["novice", "intermediate", "advanced", "expert"] 
        }'::jsonb
)
`

func (q *Queries) InsertProficiencyLevelOutput(ctx context.Context, coursePhaseTypeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertProficiencyLevelOutput, coursePhaseTypeID)
	return err
}

const testApplicationPhaseTypeExists = `-- name: TestApplicationPhaseTypeExists :one
SELECT EXISTS (
    SELECT 1
    FROM course_phase_type
    WHERE name = 'Application'
) AS does_exist
`

func (q *Queries) TestApplicationPhaseTypeExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, testApplicationPhaseTypeExists)
	var does_exist bool
	err := row.Scan(&does_exist)
	return does_exist, err
}

const testAssessmentTypeExists = `-- name: TestAssessmentTypeExists :one
SELECT EXISTS (
    SELECT 1
    FROM course_phase_type
    WHERE name = 'Assessment'
) AS does_exist
`

func (q *Queries) TestAssessmentTypeExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, testAssessmentTypeExists)
	var does_exist bool
	err := row.Scan(&does_exist)
	return does_exist, err
}

const testDevOpsChallengeTypeExists = `-- name: TestDevOpsChallengeTypeExists :one
SELECT EXISTS (
    SELECT 1
    FROM course_phase_type
    WHERE name = 'DevOpsChallenge'
) AS does_exist
`

func (q *Queries) TestDevOpsChallengeTypeExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, testDevOpsChallengeTypeExists)
	var does_exist bool
	err := row.Scan(&does_exist)
	return does_exist, err
}

const testInterviewPhaseTypeExists = `-- name: TestInterviewPhaseTypeExists :one
SELECT EXISTS (
    SELECT 1
    FROM course_phase_type
    WHERE name = 'Interview'
) AS does_exist
`

func (q *Queries) TestInterviewPhaseTypeExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, testInterviewPhaseTypeExists)
	var does_exist bool
	err := row.Scan(&does_exist)
	return does_exist, err
}

const testIntroCourseDeveloperPhaseTypeExists = `-- name: TestIntroCourseDeveloperPhaseTypeExists :one
SELECT EXISTS (
    SELECT 1
    FROM course_phase_type
    WHERE name = 'IntroCourseDeveloper'
) AS does_exist
`

func (q *Queries) TestIntroCourseDeveloperPhaseTypeExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, testIntroCourseDeveloperPhaseTypeExists)
	var does_exist bool
	err := row.Scan(&does_exist)
	return does_exist, err
}

const testIntroCourseTutorPhaseTypeExists = `-- name: TestIntroCourseTutorPhaseTypeExists :one
SELECT EXISTS (
    SELECT 1
    FROM course_phase_type
    WHERE name = 'IntroCourseTutor'
) AS does_exist
`

func (q *Queries) TestIntroCourseTutorPhaseTypeExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, testIntroCourseTutorPhaseTypeExists)
	var does_exist bool
	err := row.Scan(&does_exist)
	return does_exist, err
}

const testMatchingPhaseTypeExists = `-- name: TestMatchingPhaseTypeExists :one
SELECT EXISTS (
    SELECT 1
    FROM course_phase_type
    WHERE name = 'Matching'
) AS does_exist
`

func (q *Queries) TestMatchingPhaseTypeExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, testMatchingPhaseTypeExists)
	var does_exist bool
	err := row.Scan(&does_exist)
	return does_exist, err
}
