// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: resolution.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLocalResolution = `-- name: GetLocalResolution :one
SELECT cpt.local_url
FROM course_phase_type cpt
JOIN course_phase cp ON cp.course_phase_type_id = cpt.id
WHERE cp.id = $1
`

func (q *Queries) GetLocalResolution(ctx context.Context, id uuid.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getLocalResolution, id)
	var local_url pgtype.Text
	err := row.Scan(&local_url)
	return local_url, err
}
