services:
  db:
    image: 'postgres:15.2-alpine'
    container_name: prompt-core-db
    environment:
      - POSTGRES_USER=prompt-postgres
      - POSTGRES_PASSWORD=prompt-postgres
      - POSTGRES_DB=prompt
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d prompt -U prompt-postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

