// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Assignment struct {
	ID                    uuid.UUID        `json:"id"`
	CourseParticipationID uuid.UUID        `json:"course_participation_id"`
	StudentFullName       string           `json:"student_full_name"`
	TeamID                uuid.UUID        `json:"team_id"`
	CoursePhaseID         uuid.UUID        `json:"course_phase_id"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

type Team struct {
	ID            uuid.UUID        `json:"id"`
	Name          string           `json:"name"`
	CoursePhaseID uuid.UUID        `json:"course_phase_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}
