// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: application.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkIfCoursePhaseIsApplicationPhase = `-- name: CheckIfCoursePhaseIsApplicationPhase :one
SELECT 
    cpt.name = 'Application' AS is_application
FROM 
    course_phase cp
JOIN 
    course_phase_type cpt
ON 
    cp.course_phase_type_id = cpt.id
WHERE 
    cp.id = $1
`

func (q *Queries) CheckIfCoursePhaseIsApplicationPhase(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkIfCoursePhaseIsApplicationPhase, id)
	var is_application bool
	err := row.Scan(&is_application)
	return is_application, err
}

const checkIfCoursePhaseIsOpenApplicationPhase = `-- name: CheckIfCoursePhaseIsOpenApplicationPhase :one
SELECT 
    cpt.name = 'Application' AS is_application
FROM 
    course_phase cp
JOIN 
    course_phase_type cpt
ON 
    cp.course_phase_type_id = cpt.id
WHERE 
    cp.id = $1
    AND (cp.meta_data->>'applicationEndDate')::timestamp > NOW()
`

func (q *Queries) CheckIfCoursePhaseIsOpenApplicationPhase(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkIfCoursePhaseIsOpenApplicationPhase, id)
	var is_application bool
	err := row.Scan(&is_application)
	return is_application, err
}

const createApplicationAnswerMultiSelect = `-- name: CreateApplicationAnswerMultiSelect :exec
INSERT INTO application_answer_multi_select (id, application_question_id, course_phase_participation_id, answer)
VALUES ($1, $2, $3, $4)
`

type CreateApplicationAnswerMultiSelectParams struct {
	ID                         uuid.UUID `json:"id"`
	ApplicationQuestionID      uuid.UUID `json:"application_question_id"`
	CoursePhaseParticipationID uuid.UUID `json:"course_phase_participation_id"`
	Answer                     []string  `json:"answer"`
}

func (q *Queries) CreateApplicationAnswerMultiSelect(ctx context.Context, arg CreateApplicationAnswerMultiSelectParams) error {
	_, err := q.db.Exec(ctx, createApplicationAnswerMultiSelect,
		arg.ID,
		arg.ApplicationQuestionID,
		arg.CoursePhaseParticipationID,
		arg.Answer,
	)
	return err
}

const createApplicationAnswerText = `-- name: CreateApplicationAnswerText :exec
INSERT INTO application_answer_text (id, application_question_id, course_phase_participation_id, answer)
VALUES ($1, $2, $3, $4)
`

type CreateApplicationAnswerTextParams struct {
	ID                         uuid.UUID   `json:"id"`
	ApplicationQuestionID      uuid.UUID   `json:"application_question_id"`
	CoursePhaseParticipationID uuid.UUID   `json:"course_phase_participation_id"`
	Answer                     pgtype.Text `json:"answer"`
}

func (q *Queries) CreateApplicationAnswerText(ctx context.Context, arg CreateApplicationAnswerTextParams) error {
	_, err := q.db.Exec(ctx, createApplicationAnswerText,
		arg.ID,
		arg.ApplicationQuestionID,
		arg.CoursePhaseParticipationID,
		arg.Answer,
	)
	return err
}

const createApplicationQuestionMultiSelect = `-- name: CreateApplicationQuestionMultiSelect :exec
INSERT INTO application_question_multi_select (id, course_phase_id, title, description, placeholder, error_message, is_required, min_select, max_select, options, order_num)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateApplicationQuestionMultiSelectParams struct {
	ID            uuid.UUID   `json:"id"`
	CoursePhaseID uuid.UUID   `json:"course_phase_id"`
	Title         pgtype.Text `json:"title"`
	Description   pgtype.Text `json:"description"`
	Placeholder   pgtype.Text `json:"placeholder"`
	ErrorMessage  pgtype.Text `json:"error_message"`
	IsRequired    pgtype.Bool `json:"is_required"`
	MinSelect     pgtype.Int4 `json:"min_select"`
	MaxSelect     pgtype.Int4 `json:"max_select"`
	Options       []string    `json:"options"`
	OrderNum      pgtype.Int4 `json:"order_num"`
}

func (q *Queries) CreateApplicationQuestionMultiSelect(ctx context.Context, arg CreateApplicationQuestionMultiSelectParams) error {
	_, err := q.db.Exec(ctx, createApplicationQuestionMultiSelect,
		arg.ID,
		arg.CoursePhaseID,
		arg.Title,
		arg.Description,
		arg.Placeholder,
		arg.ErrorMessage,
		arg.IsRequired,
		arg.MinSelect,
		arg.MaxSelect,
		arg.Options,
		arg.OrderNum,
	)
	return err
}

const createApplicationQuestionText = `-- name: CreateApplicationQuestionText :exec
INSERT INTO application_question_text (id, course_phase_id, title, description, placeholder, validation_regex, error_message, is_required, allowed_length, order_num)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateApplicationQuestionTextParams struct {
	ID              uuid.UUID   `json:"id"`
	CoursePhaseID   uuid.UUID   `json:"course_phase_id"`
	Title           pgtype.Text `json:"title"`
	Description     pgtype.Text `json:"description"`
	Placeholder     pgtype.Text `json:"placeholder"`
	ValidationRegex pgtype.Text `json:"validation_regex"`
	ErrorMessage    pgtype.Text `json:"error_message"`
	IsRequired      pgtype.Bool `json:"is_required"`
	AllowedLength   pgtype.Int4 `json:"allowed_length"`
	OrderNum        pgtype.Int4 `json:"order_num"`
}

func (q *Queries) CreateApplicationQuestionText(ctx context.Context, arg CreateApplicationQuestionTextParams) error {
	_, err := q.db.Exec(ctx, createApplicationQuestionText,
		arg.ID,
		arg.CoursePhaseID,
		arg.Title,
		arg.Description,
		arg.Placeholder,
		arg.ValidationRegex,
		arg.ErrorMessage,
		arg.IsRequired,
		arg.AllowedLength,
		arg.OrderNum,
	)
	return err
}

const createOrOverwriteApplicationAnswerMultiSelect = `-- name: CreateOrOverwriteApplicationAnswerMultiSelect :exec
INSERT INTO application_answer_multi_select (id, application_question_id, course_phase_participation_id, answer)
VALUES ($1, $2, $3, $4)
ON CONFLICT (course_phase_participation_id, application_question_id)
DO UPDATE
SET answer = EXCLUDED.answer
`

type CreateOrOverwriteApplicationAnswerMultiSelectParams struct {
	ID                         uuid.UUID `json:"id"`
	ApplicationQuestionID      uuid.UUID `json:"application_question_id"`
	CoursePhaseParticipationID uuid.UUID `json:"course_phase_participation_id"`
	Answer                     []string  `json:"answer"`
}

func (q *Queries) CreateOrOverwriteApplicationAnswerMultiSelect(ctx context.Context, arg CreateOrOverwriteApplicationAnswerMultiSelectParams) error {
	_, err := q.db.Exec(ctx, createOrOverwriteApplicationAnswerMultiSelect,
		arg.ID,
		arg.ApplicationQuestionID,
		arg.CoursePhaseParticipationID,
		arg.Answer,
	)
	return err
}

const createOrOverwriteApplicationAnswerText = `-- name: CreateOrOverwriteApplicationAnswerText :exec
INSERT INTO application_answer_text (id, application_question_id, course_phase_participation_id, answer)
VALUES ($1, $2, $3, $4)
ON CONFLICT (course_phase_participation_id, application_question_id)
DO UPDATE
SET answer = EXCLUDED.answer
`

type CreateOrOverwriteApplicationAnswerTextParams struct {
	ID                         uuid.UUID   `json:"id"`
	ApplicationQuestionID      uuid.UUID   `json:"application_question_id"`
	CoursePhaseParticipationID uuid.UUID   `json:"course_phase_participation_id"`
	Answer                     pgtype.Text `json:"answer"`
}

func (q *Queries) CreateOrOverwriteApplicationAnswerText(ctx context.Context, arg CreateOrOverwriteApplicationAnswerTextParams) error {
	_, err := q.db.Exec(ctx, createOrOverwriteApplicationAnswerText,
		arg.ID,
		arg.ApplicationQuestionID,
		arg.CoursePhaseParticipationID,
		arg.Answer,
	)
	return err
}

const deleteApplicationQuestionMultiSelect = `-- name: DeleteApplicationQuestionMultiSelect :exec
DELETE FROM application_question_multi_select
WHERE id = $1
`

func (q *Queries) DeleteApplicationQuestionMultiSelect(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplicationQuestionMultiSelect, id)
	return err
}

const deleteApplicationQuestionText = `-- name: DeleteApplicationQuestionText :exec
DELETE FROM application_question_text
WHERE id = $1
`

func (q *Queries) DeleteApplicationQuestionText(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplicationQuestionText, id)
	return err
}

const getAllApplicationParticipations = `-- name: GetAllApplicationParticipations :many
SELECT
    cpp.id AS course_phase_participation_id,
    cpp.pass_status,
    cpp.meta_data,
    s.id AS student_id,
    s.first_name,
    s.last_name,
    s.email,
    s.matriculation_number,
    s.university_login,
    s.has_university_account,
    s.gender, 
    a.score
FROM
    course_phase_participation cpp
JOIN
    course_participation cp ON cpp.course_participation_id = cp.id
JOIN
    student s ON cp.student_id = s.id
LEFT JOIN
    application_assessment a on cpp.id = a.course_phase_participation_id
WHERE
    cpp.course_phase_id = $1
`

type GetAllApplicationParticipationsRow struct {
	CoursePhaseParticipationID uuid.UUID      `json:"course_phase_participation_id"`
	PassStatus                 NullPassStatus `json:"pass_status"`
	MetaData                   []byte         `json:"meta_data"`
	StudentID                  uuid.UUID      `json:"student_id"`
	FirstName                  pgtype.Text    `json:"first_name"`
	LastName                   pgtype.Text    `json:"last_name"`
	Email                      pgtype.Text    `json:"email"`
	MatriculationNumber        pgtype.Text    `json:"matriculation_number"`
	UniversityLogin            pgtype.Text    `json:"university_login"`
	HasUniversityAccount       pgtype.Bool    `json:"has_university_account"`
	Gender                     Gender         `json:"gender"`
	Score                      pgtype.Int4    `json:"score"`
}

func (q *Queries) GetAllApplicationParticipations(ctx context.Context, coursePhaseID uuid.UUID) ([]GetAllApplicationParticipationsRow, error) {
	rows, err := q.db.Query(ctx, getAllApplicationParticipations, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllApplicationParticipationsRow
	for rows.Next() {
		var i GetAllApplicationParticipationsRow
		if err := rows.Scan(
			&i.CoursePhaseParticipationID,
			&i.PassStatus,
			&i.MetaData,
			&i.StudentID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.MatriculationNumber,
			&i.UniversityLogin,
			&i.HasUniversityAccount,
			&i.Gender,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllOpenApplicationPhases = `-- name: GetAllOpenApplicationPhases :many
SELECT 
    cp.id AS course_phase_id,
    c.name AS course_name,
    c.start_date, 
    c.end_date,
    c.course_type, 
    c.ects,
    (cp.meta_data->>'applicationEndDate')::text AS application_end_date,
    (cp.meta_data->>'externalStudentsAllowed')::boolean AS external_students_allowed
FROM 
    course_phase cp
JOIN 
    course_phase_type cpt
    ON cp.course_phase_type_id = cpt.id
JOIN 
    course c
    ON cp.course_id = c.id
WHERE 
    cp.is_initial_phase = true
    AND cpt.name = 'Application'
    AND (cp.meta_data->>'applicationEndDate')::timestamp > NOW()
    AND (cp.meta_data->>'applicationStartDate')::timestamp < NOW()
`

type GetAllOpenApplicationPhasesRow struct {
	CoursePhaseID           uuid.UUID   `json:"course_phase_id"`
	CourseName              string      `json:"course_name"`
	StartDate               pgtype.Date `json:"start_date"`
	EndDate                 pgtype.Date `json:"end_date"`
	CourseType              CourseType  `json:"course_type"`
	Ects                    pgtype.Int4 `json:"ects"`
	ApplicationEndDate      string      `json:"application_end_date"`
	ExternalStudentsAllowed bool        `json:"external_students_allowed"`
}

func (q *Queries) GetAllOpenApplicationPhases(ctx context.Context) ([]GetAllOpenApplicationPhasesRow, error) {
	rows, err := q.db.Query(ctx, getAllOpenApplicationPhases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllOpenApplicationPhasesRow
	for rows.Next() {
		var i GetAllOpenApplicationPhasesRow
		if err := rows.Scan(
			&i.CoursePhaseID,
			&i.CourseName,
			&i.StartDate,
			&i.EndDate,
			&i.CourseType,
			&i.Ects,
			&i.ApplicationEndDate,
			&i.ExternalStudentsAllowed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationAnswersMultiSelectForStudent = `-- name: GetApplicationAnswersMultiSelectForStudent :many
SELECT aams.id, aams.application_question_id, aams.course_phase_participation_id, aams.answer
FROM application_answer_multi_select aams
INNER JOIN course_phase_participation cpp ON aams.course_phase_participation_id = cpp.id
INNER JOIN course_participation cp ON cpp.course_participation_id = cp.id
WHERE cp.student_id = $1 AND cpp.course_phase_id = $2
`

type GetApplicationAnswersMultiSelectForStudentParams struct {
	StudentID     uuid.UUID `json:"student_id"`
	CoursePhaseID uuid.UUID `json:"course_phase_id"`
}

func (q *Queries) GetApplicationAnswersMultiSelectForStudent(ctx context.Context, arg GetApplicationAnswersMultiSelectForStudentParams) ([]ApplicationAnswerMultiSelect, error) {
	rows, err := q.db.Query(ctx, getApplicationAnswersMultiSelectForStudent, arg.StudentID, arg.CoursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationAnswerMultiSelect
	for rows.Next() {
		var i ApplicationAnswerMultiSelect
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationQuestionID,
			&i.CoursePhaseParticipationID,
			&i.Answer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationAnswersTextForStudent = `-- name: GetApplicationAnswersTextForStudent :many
SELECT aat.id, aat.application_question_id, aat.course_phase_participation_id, aat.answer
FROM application_answer_text aat
INNER JOIN course_phase_participation cpp ON aat.course_phase_participation_id = cpp.id
INNER JOIN course_participation cp ON cpp.course_participation_id = cp.id
WHERE cp.student_id = $1 AND cpp.course_phase_id = $2
`

type GetApplicationAnswersTextForStudentParams struct {
	StudentID     uuid.UUID `json:"student_id"`
	CoursePhaseID uuid.UUID `json:"course_phase_id"`
}

func (q *Queries) GetApplicationAnswersTextForStudent(ctx context.Context, arg GetApplicationAnswersTextForStudentParams) ([]ApplicationAnswerText, error) {
	rows, err := q.db.Query(ctx, getApplicationAnswersTextForStudent, arg.StudentID, arg.CoursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationAnswerText
	for rows.Next() {
		var i ApplicationAnswerText
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationQuestionID,
			&i.CoursePhaseParticipationID,
			&i.Answer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationExists = `-- name: GetApplicationExists :one
SELECT EXISTS (
    SELECT 1
    FROM course_phase_participation cpp
    WHERE cpp.course_phase_id = $1
    AND cpp.id = $2
)
`

type GetApplicationExistsParams struct {
	CoursePhaseID uuid.UUID `json:"course_phase_id"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) GetApplicationExists(ctx context.Context, arg GetApplicationExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, getApplicationExists, arg.CoursePhaseID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getApplicationExistsForStudent = `-- name: GetApplicationExistsForStudent :one
SELECT EXISTS (
    SELECT 1
    FROM course_participation cp
    INNER JOIN course_phase ph ON cp.course_id = ph.course_id
    WHERE cp.student_id = $1 AND ph.id = $2
)
`

type GetApplicationExistsForStudentParams struct {
	StudentID uuid.UUID `json:"student_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetApplicationExistsForStudent(ctx context.Context, arg GetApplicationExistsForStudentParams) (bool, error) {
	row := q.db.QueryRow(ctx, getApplicationExistsForStudent, arg.StudentID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getApplicationQuestionsMultiSelectForCoursePhase = `-- name: GetApplicationQuestionsMultiSelectForCoursePhase :many
SELECT id, course_phase_id, title, description, placeholder, error_message, is_required, min_select, max_select, options, order_num FROM application_question_multi_select
WHERE course_phase_id = $1
`

func (q *Queries) GetApplicationQuestionsMultiSelectForCoursePhase(ctx context.Context, coursePhaseID uuid.UUID) ([]ApplicationQuestionMultiSelect, error) {
	rows, err := q.db.Query(ctx, getApplicationQuestionsMultiSelectForCoursePhase, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationQuestionMultiSelect
	for rows.Next() {
		var i ApplicationQuestionMultiSelect
		if err := rows.Scan(
			&i.ID,
			&i.CoursePhaseID,
			&i.Title,
			&i.Description,
			&i.Placeholder,
			&i.ErrorMessage,
			&i.IsRequired,
			&i.MinSelect,
			&i.MaxSelect,
			&i.Options,
			&i.OrderNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationQuestionsTextForCoursePhase = `-- name: GetApplicationQuestionsTextForCoursePhase :many
SELECT id, course_phase_id, title, description, placeholder, validation_regex, error_message, is_required, allowed_length, order_num FROM application_question_text
WHERE course_phase_id = $1
`

func (q *Queries) GetApplicationQuestionsTextForCoursePhase(ctx context.Context, coursePhaseID uuid.UUID) ([]ApplicationQuestionText, error) {
	rows, err := q.db.Query(ctx, getApplicationQuestionsTextForCoursePhase, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationQuestionText
	for rows.Next() {
		var i ApplicationQuestionText
		if err := rows.Scan(
			&i.ID,
			&i.CoursePhaseID,
			&i.Title,
			&i.Description,
			&i.Placeholder,
			&i.ValidationRegex,
			&i.ErrorMessage,
			&i.IsRequired,
			&i.AllowedLength,
			&i.OrderNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenApplicationPhase = `-- name: GetOpenApplicationPhase :one
SELECT 
    cp.id AS course_phase_id,
    c.name AS course_name,
    c.start_date, 
    c.end_date,
    c.course_type, 
    c.ects,
    (cp.meta_data->>'applicationEndDate')::text AS application_end_date,
    (cp.meta_data->>'externalStudentsAllowed')::boolean AS external_students_allowed
FROM 
    course_phase cp
JOIN 
    course_phase_type cpt
    ON cp.course_phase_type_id = cpt.id
JOIN 
    course c
    ON cp.course_id = c.id
WHERE 
    cp.id = $1
    AND cp.is_initial_phase = true
    AND cpt.name = 'Application'
    AND (cp.meta_data->>'applicationEndDate')::timestamp > NOW()
    AND (cp.meta_data->>'applicationStartDate')::timestamp < NOW()
`

type GetOpenApplicationPhaseRow struct {
	CoursePhaseID           uuid.UUID   `json:"course_phase_id"`
	CourseName              string      `json:"course_name"`
	StartDate               pgtype.Date `json:"start_date"`
	EndDate                 pgtype.Date `json:"end_date"`
	CourseType              CourseType  `json:"course_type"`
	Ects                    pgtype.Int4 `json:"ects"`
	ApplicationEndDate      string      `json:"application_end_date"`
	ExternalStudentsAllowed bool        `json:"external_students_allowed"`
}

func (q *Queries) GetOpenApplicationPhase(ctx context.Context, id uuid.UUID) (GetOpenApplicationPhaseRow, error) {
	row := q.db.QueryRow(ctx, getOpenApplicationPhase, id)
	var i GetOpenApplicationPhaseRow
	err := row.Scan(
		&i.CoursePhaseID,
		&i.CourseName,
		&i.StartDate,
		&i.EndDate,
		&i.CourseType,
		&i.Ects,
		&i.ApplicationEndDate,
		&i.ExternalStudentsAllowed,
	)
	return i, err
}

const updateApplicationQuestionMultiSelect = `-- name: UpdateApplicationQuestionMultiSelect :exec
UPDATE application_question_multi_select
SET
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    placeholder = COALESCE($4, placeholder),
    error_message = COALESCE($5, error_message),
    is_required = COALESCE($6, is_required),
    min_select = COALESCE($7, min_select),
    max_select = COALESCE($8, max_select),
    options = COALESCE($9, options),
    order_num = COALESCE($10, order_num)
WHERE id = $1
`

type UpdateApplicationQuestionMultiSelectParams struct {
	ID           uuid.UUID   `json:"id"`
	Title        pgtype.Text `json:"title"`
	Description  pgtype.Text `json:"description"`
	Placeholder  pgtype.Text `json:"placeholder"`
	ErrorMessage pgtype.Text `json:"error_message"`
	IsRequired   pgtype.Bool `json:"is_required"`
	MinSelect    pgtype.Int4 `json:"min_select"`
	MaxSelect    pgtype.Int4 `json:"max_select"`
	Options      []string    `json:"options"`
	OrderNum     pgtype.Int4 `json:"order_num"`
}

func (q *Queries) UpdateApplicationQuestionMultiSelect(ctx context.Context, arg UpdateApplicationQuestionMultiSelectParams) error {
	_, err := q.db.Exec(ctx, updateApplicationQuestionMultiSelect,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Placeholder,
		arg.ErrorMessage,
		arg.IsRequired,
		arg.MinSelect,
		arg.MaxSelect,
		arg.Options,
		arg.OrderNum,
	)
	return err
}

const updateApplicationQuestionText = `-- name: UpdateApplicationQuestionText :exec
UPDATE application_question_text
SET
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    placeholder = COALESCE($4, placeholder),
    validation_regex = COALESCE($5, validation_regex),
    error_message = COALESCE($6, error_message),
    is_required = COALESCE($7, is_required),
    allowed_length = COALESCE($8, allowed_length),
    order_num = COALESCE($9, order_num)
WHERE id = $1
`

type UpdateApplicationQuestionTextParams struct {
	ID              uuid.UUID   `json:"id"`
	Title           pgtype.Text `json:"title"`
	Description     pgtype.Text `json:"description"`
	Placeholder     pgtype.Text `json:"placeholder"`
	ValidationRegex pgtype.Text `json:"validation_regex"`
	ErrorMessage    pgtype.Text `json:"error_message"`
	IsRequired      pgtype.Bool `json:"is_required"`
	AllowedLength   pgtype.Int4 `json:"allowed_length"`
	OrderNum        pgtype.Int4 `json:"order_num"`
}

func (q *Queries) UpdateApplicationQuestionText(ctx context.Context, arg UpdateApplicationQuestionTextParams) error {
	_, err := q.db.Exec(ctx, updateApplicationQuestionText,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Placeholder,
		arg.ValidationRegex,
		arg.ErrorMessage,
		arg.IsRequired,
		arg.AllowedLength,
		arg.OrderNum,
	)
	return err
}
