// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: course_phase_participation.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCoursePhaseParticipation = `-- name: CreateCoursePhaseParticipation :one
INSERT INTO course_phase_participation (id, course_participation_id, course_phase_id, passed, meta_data)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, course_participation_id, course_phase_id, passed, meta_data
`

type CreateCoursePhaseParticipationParams struct {
	ID                    uuid.UUID   `json:"id"`
	CourseParticipationID uuid.UUID   `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID   `json:"course_phase_id"`
	Passed                pgtype.Bool `json:"passed"`
	MetaData              []byte      `json:"meta_data"`
}

func (q *Queries) CreateCoursePhaseParticipation(ctx context.Context, arg CreateCoursePhaseParticipationParams) (CoursePhaseParticipation, error) {
	row := q.db.QueryRow(ctx, createCoursePhaseParticipation,
		arg.ID,
		arg.CourseParticipationID,
		arg.CoursePhaseID,
		arg.Passed,
		arg.MetaData,
	)
	var i CoursePhaseParticipation
	err := row.Scan(
		&i.ID,
		&i.CourseParticipationID,
		&i.CoursePhaseID,
		&i.Passed,
		&i.MetaData,
	)
	return i, err
}

const getAllCoursePhaseParticipationsForCourseParticipation = `-- name: GetAllCoursePhaseParticipationsForCourseParticipation :many
SELECT id, course_participation_id, course_phase_id, passed, meta_data FROM course_phase_participation
WHERE course_participation_id = $1
`

func (q *Queries) GetAllCoursePhaseParticipationsForCourseParticipation(ctx context.Context, courseParticipationID uuid.UUID) ([]CoursePhaseParticipation, error) {
	rows, err := q.db.Query(ctx, getAllCoursePhaseParticipationsForCourseParticipation, courseParticipationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursePhaseParticipation
	for rows.Next() {
		var i CoursePhaseParticipation
		if err := rows.Scan(
			&i.ID,
			&i.CourseParticipationID,
			&i.CoursePhaseID,
			&i.Passed,
			&i.MetaData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCoursePhaseParticipationsForCoursePhase = `-- name: GetAllCoursePhaseParticipationsForCoursePhase :many
SELECT
    cpp.id AS course_phase_participation_id,
    cpp.passed,
    cpp.meta_data,
    s.id AS student_id,
    s.first_name,
    s.last_name,
    s.email,
    s.matriculation_number,
    s.university_login,
    s.has_university_account,
    s.gender
FROM
    course_phase_participation cpp
JOIN
    course_participation cp ON cpp.course_participation_id = cp.id
JOIN
    student s ON cp.student_id = s.id
WHERE
    cpp.course_phase_id = $1
`

type GetAllCoursePhaseParticipationsForCoursePhaseRow struct {
	CoursePhaseParticipationID uuid.UUID   `json:"course_phase_participation_id"`
	Passed                     pgtype.Bool `json:"passed"`
	MetaData                   []byte      `json:"meta_data"`
	StudentID                  uuid.UUID   `json:"student_id"`
	FirstName                  pgtype.Text `json:"first_name"`
	LastName                   pgtype.Text `json:"last_name"`
	Email                      pgtype.Text `json:"email"`
	MatriculationNumber        pgtype.Text `json:"matriculation_number"`
	UniversityLogin            pgtype.Text `json:"university_login"`
	HasUniversityAccount       pgtype.Bool `json:"has_university_account"`
	Gender                     Gender      `json:"gender"`
}

func (q *Queries) GetAllCoursePhaseParticipationsForCoursePhase(ctx context.Context, coursePhaseID uuid.UUID) ([]GetAllCoursePhaseParticipationsForCoursePhaseRow, error) {
	rows, err := q.db.Query(ctx, getAllCoursePhaseParticipationsForCoursePhase, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCoursePhaseParticipationsForCoursePhaseRow
	for rows.Next() {
		var i GetAllCoursePhaseParticipationsForCoursePhaseRow
		if err := rows.Scan(
			&i.CoursePhaseParticipationID,
			&i.Passed,
			&i.MetaData,
			&i.StudentID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.MatriculationNumber,
			&i.UniversityLogin,
			&i.HasUniversityAccount,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursePhaseParticipation = `-- name: GetCoursePhaseParticipation :one
SELECT id, course_participation_id, course_phase_id, passed, meta_data FROM course_phase_participation
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCoursePhaseParticipation(ctx context.Context, id uuid.UUID) (CoursePhaseParticipation, error) {
	row := q.db.QueryRow(ctx, getCoursePhaseParticipation, id)
	var i CoursePhaseParticipation
	err := row.Scan(
		&i.ID,
		&i.CourseParticipationID,
		&i.CoursePhaseID,
		&i.Passed,
		&i.MetaData,
	)
	return i, err
}

const getCoursePhaseParticipationByCourseParticipationAndCoursePhase = `-- name: GetCoursePhaseParticipationByCourseParticipationAndCoursePhase :one
SELECT id, course_participation_id, course_phase_id, passed, meta_data FROM course_phase_participation
WHERE course_participation_id = $1 AND course_phase_id = $2 LIMIT 1
`

type GetCoursePhaseParticipationByCourseParticipationAndCoursePhaseParams struct {
	CourseParticipationID uuid.UUID `json:"course_participation_id"`
	CoursePhaseID         uuid.UUID `json:"course_phase_id"`
}

func (q *Queries) GetCoursePhaseParticipationByCourseParticipationAndCoursePhase(ctx context.Context, arg GetCoursePhaseParticipationByCourseParticipationAndCoursePhaseParams) (CoursePhaseParticipation, error) {
	row := q.db.QueryRow(ctx, getCoursePhaseParticipationByCourseParticipationAndCoursePhase, arg.CourseParticipationID, arg.CoursePhaseID)
	var i CoursePhaseParticipation
	err := row.Scan(
		&i.ID,
		&i.CourseParticipationID,
		&i.CoursePhaseID,
		&i.Passed,
		&i.MetaData,
	)
	return i, err
}

const updateCoursePhaseParticipation = `-- name: UpdateCoursePhaseParticipation :one
UPDATE course_phase_participation
SET 
    passed = COALESCE($2, passed),
    meta_data = meta_data || $3
WHERE id = $1
RETURNING id, course_participation_id, course_phase_id, passed, meta_data
`

type UpdateCoursePhaseParticipationParams struct {
	ID       uuid.UUID   `json:"id"`
	Passed   pgtype.Bool `json:"passed"`
	MetaData []byte      `json:"meta_data"`
}

func (q *Queries) UpdateCoursePhaseParticipation(ctx context.Context, arg UpdateCoursePhaseParticipationParams) (CoursePhaseParticipation, error) {
	row := q.db.QueryRow(ctx, updateCoursePhaseParticipation, arg.ID, arg.Passed, arg.MetaData)
	var i CoursePhaseParticipation
	err := row.Scan(
		&i.ID,
		&i.CourseParticipationID,
		&i.CoursePhaseID,
		&i.Passed,
		&i.MetaData,
	)
	return i, err
}
