// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: course_phase.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCoursePhase = `-- name: CreateCoursePhase :one
INSERT INTO course_phase (id, course_id, name, is_initial_phase, meta_data)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, course_id, name, meta_data, is_initial_phase, course_phase_type_id
`

type CreateCoursePhaseParams struct {
	ID             uuid.UUID   `json:"id"`
	CourseID       uuid.UUID   `json:"course_id"`
	Name           pgtype.Text `json:"name"`
	IsInitialPhase bool        `json:"is_initial_phase"`
	MetaData       []byte      `json:"meta_data"`
}

func (q *Queries) CreateCoursePhase(ctx context.Context, arg CreateCoursePhaseParams) (CoursePhase, error) {
	row := q.db.QueryRow(ctx, createCoursePhase,
		arg.ID,
		arg.CourseID,
		arg.Name,
		arg.IsInitialPhase,
		arg.MetaData,
	)
	var i CoursePhase
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Name,
		&i.MetaData,
		&i.IsInitialPhase,
		&i.CoursePhaseTypeID,
	)
	return i, err
}

const getAllCoursePhaseForCourse = `-- name: GetAllCoursePhaseForCourse :many
SELECT id, course_id, name, meta_data, is_initial_phase, course_phase_type_id FROM course_phase
WHERE course_id = $1
`

func (q *Queries) GetAllCoursePhaseForCourse(ctx context.Context, courseID uuid.UUID) ([]CoursePhase, error) {
	rows, err := q.db.Query(ctx, getAllCoursePhaseForCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoursePhase
	for rows.Next() {
		var i CoursePhase
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Name,
			&i.MetaData,
			&i.IsInitialPhase,
			&i.CoursePhaseTypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursePhase = `-- name: GetCoursePhase :one
SELECT id, course_id, name, meta_data, is_initial_phase, course_phase_type_id FROM course_phase
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCoursePhase(ctx context.Context, id uuid.UUID) (CoursePhase, error) {
	row := q.db.QueryRow(ctx, getCoursePhase, id)
	var i CoursePhase
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Name,
		&i.MetaData,
		&i.IsInitialPhase,
		&i.CoursePhaseTypeID,
	)
	return i, err
}

const updateCoursePhase = `-- name: UpdateCoursePhase :exec
UPDATE course_phase
SET 
    name = COALESCE($2, name), 
    is_initial_phase = COALESCE($3, is_initial_phase), 
    meta_data = meta_data || $4
WHERE id = $1
`

type UpdateCoursePhaseParams struct {
	ID             uuid.UUID   `json:"id"`
	Name           pgtype.Text `json:"name"`
	IsInitialPhase bool        `json:"is_initial_phase"`
	MetaData       []byte      `json:"meta_data"`
}

func (q *Queries) UpdateCoursePhase(ctx context.Context, arg UpdateCoursePhaseParams) error {
	_, err := q.db.Exec(ctx, updateCoursePhase,
		arg.ID,
		arg.Name,
		arg.IsInitialPhase,
		arg.MetaData,
	)
	return err
}
