// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: students.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO student (id, first_name, last_name, email, matriculation_number, university_login, has_university_account, gender)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, first_name, last_name, email, matriculation_number, university_login, has_university_account, gender
`

type CreateStudentParams struct {
	ID                   uuid.UUID   `json:"id"`
	FirstName            pgtype.Text `json:"first_name"`
	LastName             pgtype.Text `json:"last_name"`
	Email                pgtype.Text `json:"email"`
	MatriculationNumber  pgtype.Text `json:"matriculation_number"`
	UniversityLogin      pgtype.Text `json:"university_login"`
	HasUniversityAccount pgtype.Bool `json:"has_university_account"`
	Gender               Gender      `json:"gender"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.MatriculationNumber,
		arg.UniversityLogin,
		arg.HasUniversityAccount,
		arg.Gender,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.MatriculationNumber,
		&i.UniversityLogin,
		&i.HasUniversityAccount,
		&i.Gender,
	)
	return i, err
}

const getAllStudents = `-- name: GetAllStudents :many
SELECT id, first_name, last_name, email, matriculation_number, university_login, has_university_account, gender FROM student
`

func (q *Queries) GetAllStudents(ctx context.Context) ([]Student, error) {
	rows, err := q.db.Query(ctx, getAllStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.MatriculationNumber,
			&i.UniversityLogin,
			&i.HasUniversityAccount,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudent = `-- name: GetStudent :one
SELECT id, first_name, last_name, email, matriculation_number, university_login, has_university_account, gender FROM student
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStudent(ctx context.Context, id uuid.UUID) (Student, error) {
	row := q.db.QueryRow(ctx, getStudent, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.MatriculationNumber,
		&i.UniversityLogin,
		&i.HasUniversityAccount,
		&i.Gender,
	)
	return i, err
}

const getStudentByCoursePhaseParticipationID = `-- name: GetStudentByCoursePhaseParticipationID :one
SELECT s.id, s.first_name, s.last_name, s.email, s.matriculation_number, s.university_login, s.has_university_account, s.gender
FROM student s
INNER JOIN course_participation cp ON s.id = cp.student_id
INNER JOIN course_phase_participation cpp ON cp.id = cpp.course_participation_id
WHERE cpp.id = $1
`

func (q *Queries) GetStudentByCoursePhaseParticipationID(ctx context.Context, id uuid.UUID) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByCoursePhaseParticipationID, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.MatriculationNumber,
		&i.UniversityLogin,
		&i.HasUniversityAccount,
		&i.Gender,
	)
	return i, err
}

const getStudentByEmail = `-- name: GetStudentByEmail :one
SELECT id, first_name, last_name, email, matriculation_number, university_login, has_university_account, gender FROM student
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetStudentByEmail(ctx context.Context, email pgtype.Text) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByEmail, email)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.MatriculationNumber,
		&i.UniversityLogin,
		&i.HasUniversityAccount,
		&i.Gender,
	)
	return i, err
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE student
SET first_name = $2,
    last_name = $3,
    email = $4,
    matriculation_number = $5,
    university_login = $6,
    has_university_account = $7,
    gender = $8
WHERE id = $1
RETURNING id, first_name, last_name, email, matriculation_number, university_login, has_university_account, gender
`

type UpdateStudentParams struct {
	ID                   uuid.UUID   `json:"id"`
	FirstName            pgtype.Text `json:"first_name"`
	LastName             pgtype.Text `json:"last_name"`
	Email                pgtype.Text `json:"email"`
	MatriculationNumber  pgtype.Text `json:"matriculation_number"`
	UniversityLogin      pgtype.Text `json:"university_login"`
	HasUniversityAccount pgtype.Bool `json:"has_university_account"`
	Gender               Gender      `json:"gender"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudent,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.MatriculationNumber,
		arg.UniversityLogin,
		arg.HasUniversityAccount,
		arg.Gender,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.MatriculationNumber,
		&i.UniversityLogin,
		&i.HasUniversityAccount,
		&i.Gender,
	)
	return i, err
}
