// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Skill struct {
	ID            uuid.UUID `json:"id"`
	CoursePhaseID uuid.UUID `json:"course_phase_id"`
	Name          string    `json:"name"`
}

type StudentSkillResponse struct {
	CourseParticipationID uuid.UUID `json:"course_participation_id"`
	SkillID               uuid.UUID `json:"skill_id"`
	Rating                int32     `json:"rating"`
}

type StudentTeamPreferenceResponse struct {
	CourseParticipationID uuid.UUID `json:"course_participation_id"`
	TeamID                uuid.UUID `json:"team_id"`
	Preference            int32     `json:"preference"`
}

type SurveyTimeframe struct {
	CoursePhaseID  uuid.UUID        `json:"course_phase_id"`
	SurveyStart    pgtype.Timestamp `json:"survey_start"`
	SurveyDeadline pgtype.Timestamp `json:"survey_deadline"`
}

type Team struct {
	ID            uuid.UUID        `json:"id"`
	Name          string           `json:"name"`
	CoursePhaseID uuid.UUID        `json:"course_phase_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}
