// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: test.sql

package db

import (
	"context"
)

const test = `-- name: Test :many
SELECT id, name, course_phase_id, created_at FROM team
`

func (q *Queries) Test(ctx context.Context) ([]Team, error) {
	rows, err := q.db.Query(ctx, test)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CoursePhaseID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
