// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: team.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTeam = `-- name: CreateTeam :exec
INSERT INTO team (id, name, course_phase_id)
VALUES ($1, $2, $3)
`

type CreateTeamParams struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	CoursePhaseID uuid.UUID `json:"course_phase_id"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) error {
	_, err := q.db.Exec(ctx, createTeam, arg.ID, arg.Name, arg.CoursePhaseID)
	return err
}

const deleteTeam = `-- name: DeleteTeam :exec

DELETE FROM team
WHERE id = $1
AND course_phase_id = $2
`

type DeleteTeamParams struct {
	ID            uuid.UUID `json:"id"`
	CoursePhaseID uuid.UUID `json:"course_phase_id"`
}

// ensuring to update only teams in the authenticated course_phase
func (q *Queries) DeleteTeam(ctx context.Context, arg DeleteTeamParams) error {
	_, err := q.db.Exec(ctx, deleteTeam, arg.ID, arg.CoursePhaseID)
	return err
}

const getTeamsByCoursePhase = `-- name: GetTeamsByCoursePhase :many
SELECT id, name, course_phase_id, creator_course_participation_id, created_at
FROM team
WHERE course_phase_id = $1
ORDER BY name
`

func (q *Queries) GetTeamsByCoursePhase(ctx context.Context, coursePhaseID uuid.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, getTeamsByCoursePhase, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CoursePhaseID,
			&i.CreatorCourseParticipationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamsWithStudentNames = `-- name: GetTeamsWithStudentNames :many
SELECT
    t.id, t.name, t.course_phase_id, t.creator_course_participation_id, t.created_at,
    ARRAY_AGG(a.student_full_name ORDER BY a.student_full_name)::text[] AS student_names
FROM
    team t
LEFT JOIN
    assignments a ON t.id = a.team_id
WHERE
    t.course_phase_id = $1
GROUP BY
    t.id
ORDER BY
    t.name
`

type GetTeamsWithStudentNamesRow struct {
	ID                           uuid.UUID        `json:"id"`
	Name                         string           `json:"name"`
	CoursePhaseID                uuid.UUID        `json:"course_phase_id"`
	CreatorCourseParticipationID uuid.UUID        `json:"creator_course_participation_id"`
	CreatedAt                    pgtype.Timestamp `json:"created_at"`
	StudentNames                 []string         `json:"student_names"`
}

func (q *Queries) GetTeamsWithStudentNames(ctx context.Context, coursePhaseID uuid.UUID) ([]GetTeamsWithStudentNamesRow, error) {
	rows, err := q.db.Query(ctx, getTeamsWithStudentNames, coursePhaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamsWithStudentNamesRow
	for rows.Next() {
		var i GetTeamsWithStudentNamesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CoursePhaseID,
			&i.CreatorCourseParticipationID,
			&i.CreatedAt,
			&i.StudentNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeam = `-- name: UpdateTeam :exec
UPDATE team
SET name = $3
WHERE id = $1
AND course_phase_id = $2
`

type UpdateTeamParams struct {
	ID            uuid.UUID `json:"id"`
	CoursePhaseID uuid.UUID `json:"course_phase_id"`
	Name          string    `json:"name"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) error {
	_, err := q.db.Exec(ctx, updateTeam, arg.ID, arg.CoursePhaseID, arg.Name)
	return err
}
