name: Lint Assessment Component

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "clients/assessment_component/**"

jobs:
  lint-assessment:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./clients
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-lint
      - run: yarn install
      - run: yarn eslint "assessment_component/**/*.{js,jsx,ts,tsx}"
