name: Lint Intro Course Developer Component

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "clients/intro_course_developer_component/**"

jobs:
  lint-core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./clients
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-lint
      - run: yarn install
      - run: yarn eslint "intro_course_developer_component/**/*.{js,jsx,ts,tsx}"
