name: Build and Push Docker Image Server

on:
  workflow_call:

jobs:
  build-and-push-server-core:
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@main
    with:
      image-name: ghcr.io/ls1intum/prompt2/prompt-server-core # Defaults to the repository name
      docker-file: server/Dockerfile # Defaults to Dockerfile
      docker-context: ./server
    secrets: inherit
