name: Build and Push Docker Image

on:
  pull_request:
    branches: [main]

jobs:
  build-and-push-server-core:
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@main
    with:
      image-name: prompt-server-core # Defaults to the repository name
      docker-file: server/Dockerfile # Defaults to Dockerfile
      docker-context: ./server
    secrets: inherit