name: Build and Push Docker Image Server

on:
  workflow_call:
    outputs:
      server_image_tag: 
        description: "The tag of the image that was built"
        value: ${{ jobs.build-and-push-server-core.outputs.image_tag }}

jobs:
  build-and-push-server-core:
    uses: ./.github/workflows/build-and-push-docker-image.yml
    with:
      image-name: ghcr.io/ls1intum/prompt2/prompt-server-core # Defaults to the repository name
      docker-file: server/Dockerfile # Defaults to Dockerfile
      docker-context: ./server
    secrets: inherit
