name: Go Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ["core"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: "**/*.sum"
      - name: Install dependencies
        run: cd servers/${{ matrix.directory }} && go mod download
      - name: Test with Go
        env:
          TESTCONTAINERS_RYUK_DISABLED: "true"
        run: cd servers/${{ matrix.directory }} && go test ./... -json > TestResults-${{ matrix.directory }}.json
      - name: Upload Go test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.directory }}
          path: ./servers/${{ matrix.directory }}/TestResults-${{ matrix.directory }}.json
