name: Go Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [ 'server' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: "**/*.sum"
      - name: Install dependencies
        run: cd ${{ matrix.directory }} && go mod download
      - name: Find and Test Go Files
        run: |
          find ${{ matrix.directory }} -type d | while read -r dir; do
            if ls "$dir"/*.go > /dev/null 2>&1; then
              echo "Running tests in $dir"
              go test "$dir" -json >> TestResults-${{ matrix.directory }}.json
            fi
          done
      - name: Upload Go test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.directory }}
          path: ./${{ matrix.directory }}/TestResults-${{ matrix.directory }}.json
