name: Lint Intro Course Tutor Component

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "clients/intro_course_tutor_component/**"

jobs:
  lint-intro-course-tutor:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./clients
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-lint
      - run: yarn install
      - run: yarn eslint "intro_course_tutor_component/**/*.{js,jsx,ts,tsx}"
