name: Lint Core

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "clients/core/**"

jobs:
  lint-core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./clients
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-lint
      - run: yarn install
      - run: yarn eslint "core/**/*.{js,jsx,ts,tsx}"
