// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CertificateMetadatum struct {
	ID             int32              `json:"id"`
	StudentID      uuid.UUID          `json:"student_id"`
	CourseID       uuid.UUID          `json:"course_id"`
	GeneratedAt    pgtype.Timestamptz `json:"generated_at"`
	LastDownload   pgtype.Timestamptz `json:"last_download"`
	DownloadCount  int32              `json:"download_count"`
	CertificateUrl string             `json:"certificate_url"`
}
